Air-Trap: rtp::server::NetworkSyncSystem Class Reference
rtp::server::NetworkSyncSystem Class Reference
System to handle network-related operations on the server side.
#include <NetworkSyncSystem.hpp>
Public Member Functions
NetworkSyncSystem (ServerNetwork &network, ecs::Registry &registry)
Constructor for NetworkSyncSystem.
void update (float dt) override
Update system logic for one frame.
void bindSessionToEntity (uint32_t sessionId, ecs::Entity entity)
Bind a network session to an entity.
void unbindSession (uint32_t sessionId)
void handleInput (uint32_t sessionId, const net::Packet &packet)
Handle input received from a client.
void handleDisconnect (uint32_t sessionId)
Handle disconnection of a client.
uint32_t handlePlayerConnection (uint32_t sessionId, const net::Packet &packet)
Handle new player connection.
void sendPacketToEntity (uint32_t entityId, const net::Packet &packet, net::NetworkMode mode)
Send a packet to the entity associated with the given ID.
void sendPacketToSession (uint32_t sessionId, const net::Packet &packet, net::NetworkMode mode)
Send a packet to a specific session.
void sendPacketToSessions (const std::vector< uint32_t > &sessions, const net::Packet &packet, net::NetworkMode mode)
Send a packet to multiple sessions.
Public Member Functions inherited from rtp::ecs::ISystem
virtual ~ISystem () noexcept=default
Private Attributes
ServerNetwork & _network
Reference to the server network manager.
ecs::Registry & _registry
Reference to the entity registry.
std::unordered_map< uint32_t, ecs::Entity > _sessionToEntity
Map of session IDs to entities (with generation).
Detailed Description
System to handle network-related operations on the server side.
Definition at line 35 of file NetworkSyncSystem.hpp.
Constructor & Destructor Documentation
NetworkSyncSystem()
rtp::server::NetworkSyncSystem::NetworkSyncSystem (ServerNetwork & network, ecs::Registry & registry)
Constructor for NetworkSyncSystem.
Parameters
network Reference to the server network manager
registry Reference to the entity registry
Definition at line 21 of file NetworkSyncSystem.cpp.
References _network, and _registry.
Member Function Documentation
bindSessionToEntity()
void rtp::server::NetworkSyncSystem::bindSessionToEntity (uint32_t sessionId, ecs::Entity entity)
Bind a network session to an entity.
Parameters
sessionId ID of the network session
entity The entity to bind (includes both index and generation)
Definition at line 31 of file NetworkSyncSystem.cpp.
References _sessionToEntity.
handleDisconnect()
void rtp::server::NetworkSyncSystem::handleDisconnect (uint32_t sessionId)
Handle disconnection of a client.
Parameters
sessionId ID of the disconnected session
Definition at line 73 of file NetworkSyncSystem.cpp.
References _sessionToEntity, rtp::ecs::Entity::index(), and rtp::log::info().
handleInput()
void rtp::server::NetworkSyncSystem::handleInput (uint32_t sessionId, const net::Packet & packet)
Handle input received from a client.
Parameters
sessionId ID of the network session
packet Packet containing the input data
Definition at line 42 of file NetworkSyncSystem.cpp.
References _registry, _sessionToEntity, rtp::log::info(), rtp::net::InputPayload::inputMask, and rtp::ecs::components::server::InputComponent::mask.
handlePlayerConnection()
uint32_t rtp::server::NetworkSyncSystem::handlePlayerConnection (uint32_t sessionId, const net::Packet & packet)
Handle new player connection.
Parameters
sessionId ID of the new session
packet Packet containing the connection data
Definition at line 84 of file NetworkSyncSystem.cpp.
References rtp::log::info(), and rtp::net::ConnectPayload::sessionId.
sendPacketToEntity()
void rtp::server::NetworkSyncSystem::sendPacketToEntity (uint32_t entityId, const net::Packet & packet, net::NetworkMode mode)
Send a packet to the entity associated with the given ID.
Parameters
entityId ID of the target entity
packet Packet to send
mode Network mode (TCP or UDP)
Definition at line 95 of file NetworkSyncSystem.cpp.
References _network, _sessionToEntity, rtp::log::info(), and rtp::log::warning().
sendPacketToSession()
void rtp::server::NetworkSyncSystem::sendPacketToSession (uint32_t sessionId, const net::Packet & packet, net::NetworkMode mode)
Send a packet to a specific session.
Parameters
sessionId ID of the target session
packet Packet to send
mode Network mode (TCP or UDP)
Definition at line 112 of file NetworkSyncSystem.cpp.
References _network.
sendPacketToSessions()
void rtp::server::NetworkSyncSystem::sendPacketToSessions (const std::vector< uint32_t > & sessions, const net::Packet & packet, net::NetworkMode mode)
Send a packet to multiple sessions.
Parameters
sessions List of session IDs
packet Packet to send
mode Network mode (TCP or UDP)
Definition at line 119 of file NetworkSyncSystem.cpp.
References _network.
unbindSession()
void rtp::server::NetworkSyncSystem::unbindSession (uint32_t sessionId)
Definition at line 37 of file NetworkSyncSystem.cpp.
References _sessionToEntity.
update()
void rtp::server::NetworkSyncSystem::update (float dt) override virtual
Update system logic for one frame.
Parameters
dt Time elapsed since last update in seconds
Note
Currently not used
Implements rtp::ecs::ISystem.
Definition at line 26 of file NetworkSyncSystem.cpp.
Member Data Documentation
_network
ServerNetwork& rtp::server::NetworkSyncSystem::_network private
Reference to the server network manager.
Definition at line 104 of file NetworkSyncSystem.hpp.
Referenced by NetworkSyncSystem(), sendPacketToEntity(), sendPacketToSession(), and sendPacketToSessions().
_registry
ecs::Registry& rtp::server::NetworkSyncSystem::_registry private
Reference to the entity registry.
Definition at line 105 of file NetworkSyncSystem.hpp.
Referenced by NetworkSyncSystem(), and handleInput().
_sessionToEntity
std::unordered_map<uint32_t, ecs::Entity> rtp::server::NetworkSyncSystem::_sessionToEntity private
Map of session IDs to entities (with generation).
Definition at line 107 of file NetworkSyncSystem.hpp.
Referenced by bindSessionToEntity(), handleDisconnect(), handleInput(), sendPacketToEntity(), and unbindSession().
The documentation for this class was generated from the following files:
server/include/Systems/NetworkSyncSystem.hpp
server/src/Systems/NetworkSyncSystem.cpp
server/src/Systems/ServerNetworkSystem.cpp