Air-Trap: rtp::client::UISystem Class Reference
rtp::client::UISystem Class Reference
System responsible for handling menu interactions.
#include <UISystem.hpp>
Public Member Functions
UISystem (ecs::Registry &registry, sf::RenderWindow &window, Settings &settings)
void update (float dt) override
Update system logic for one frame.
void handleEvent (const sf::Event &event)
void renderGamepadCursor (sf::RenderWindow &window)
Public Member Functions inherited from rtp::ecs::ISystem
virtual ~ISystem () noexcept=default
Private Member Functions
void handleMouseMove (const sf::Vector2i &mousePos)
void handleMouseClick (const sf::Vector2i &mousePos)
void playClickSound ()
bool isMouseOverButton (const ecs::components::ui::Button &button, const sf::Vector2i &mousePos)
bool isMouseOverSlider (const ecs::components::ui::Slider &slider, const sf::Vector2i &mousePos)
bool isMouseOverDropdown (const ecs::components::ui::Dropdown &dropdown, const sf::Vector2i &mousePos)
void updateSliderValue (ecs::components::ui::Slider &slider, const sf::Vector2i &mousePos)
int getDropdownOptionAtMouse (const ecs::components::ui::Dropdown &dropdown, const sf::Vector2i &mousePos)
bool isMouseOverTextInput (const ecs::components::ui::TextInput &input, const sf::Vector2i &mousePos) const
void focusTextInputAt (const sf::Vector2i &mousePos)
void clearAllTextInputFocus ()
void handleTextEntered (std::uint32_t unicode)
void handleKeyPressed (sf::Keyboard::Key key)
void updateGamepadCursor (float dt)
void handleGamepadInput ()
Private Attributes
ecs::Registry & _registry
sf::RenderWindow & _window
Settings & _settings
sf::Vector2f _gamepadCursorPos
bool _gamepadMode {false}
sf::Clock _gamepadButtonClock
Detailed Description
System responsible for handling menu interactions.
Definition at line 31 of file UISystem.hpp.
Constructor & Destructor Documentation
UISystem()
rtp::client::UISystem::UISystem (ecs::Registry & registry, sf::RenderWindow & window, Settings & settings) inline
Definition at line 33 of file UISystem.hpp.
References _gamepadCursorPos, _registry, _settings, and _window.
Member Function Documentation
clearAllTextInputFocus()
void rtp::client::UISystem::clearAllTextInputFocus () private
Definition at line 359 of file UISystem.cpp.
References _registry, and rtp::ecs::components::ui::TextInput::value.
Referenced by handleKeyPressed().
focusTextInputAt()
void rtp::client::UISystem::focusTextInputAt (const sf::Vector2i & mousePos) private
Definition at line 374 of file UISystem.cpp.
References _registry, isMouseOverTextInput(), and rtp::ecs::components::ui::TextInput::value.
getDropdownOptionAtMouse()
int rtp::client::UISystem::getDropdownOptionAtMouse (const ecs::components::ui::Dropdown & dropdown, const sf::Vector2i & mousePos) private
Definition at line 316 of file UISystem.cpp.
References rtp::ecs::components::ui::Dropdown::options, rtp::ecs::components::ui::Dropdown::position, rtp::ecs::components::ui::Dropdown::size, rtp::Vec2< T >::x, and rtp::Vec2< T >::y.
Referenced by handleMouseClick().
handleEvent()
void rtp::client::UISystem::handleEvent (const sf::Event & event)
Definition at line 52 of file UISystem.cpp.
References handleKeyPressed(), and handleTextEntered().
handleGamepadInput()
void rtp::client::UISystem::handleGamepadInput () private
Definition at line 550 of file UISystem.cpp.
References _gamepadCursorPos, _gamepadMode, _settings, and handleMouseClick().
Referenced by update().
handleKeyPressed()
void rtp::client::UISystem::handleKeyPressed (sf::Keyboard::Key key) private
Definition at line 456 of file UISystem.cpp.
References _registry, clearAllTextInputFocus(), and rtp::ecs::components::ui::TextInput::value.
Referenced by handleEvent().
handleMouseClick()
void rtp::client::UISystem::handleMouseClick (const sf::Vector2i & mousePos) private
Definition at line 81 of file UISystem.cpp.
References _registry, getDropdownOptionAtMouse(), rtp::log::info(), isMouseOverButton(), isMouseOverDropdown(), isMouseOverSlider(), isMouseOverTextInput(), playClickSound(), rtp::ecs::components::ui::Pressed, and updateSliderValue().
Referenced by handleGamepadInput(), and update().
handleMouseMove()
void rtp::client::UISystem::handleMouseMove (const sf::Vector2i & mousePos) private
Definition at line 62 of file UISystem.cpp.
References _registry, rtp::ecs::components::ui::Hovered, rtp::ecs::components::ui::Idle, and isMouseOverButton().
Referenced by update().
handleTextEntered()
void rtp::client::UISystem::handleTextEntered (std::uint32_t unicode) private
Definition at line 399 of file UISystem.cpp.
References _registry, and rtp::ecs::components::ui::TextInput::value.
Referenced by handleEvent().
isMouseOverButton()
bool rtp::client::UISystem::isMouseOverButton (const ecs::components::ui::Button & button, const sf::Vector2i & mousePos) private
Definition at line 254 of file UISystem.cpp.
References rtp::ecs::components::ui::Button::position, rtp::ecs::components::ui::Button::size, rtp::Vec2< T >::x, and rtp::Vec2< T >::y.
Referenced by handleMouseClick(), and handleMouseMove().
isMouseOverDropdown()
bool rtp::client::UISystem::isMouseOverDropdown (const ecs::components::ui::Dropdown & dropdown, const sf::Vector2i & mousePos) private
Definition at line 286 of file UISystem.cpp.
References rtp::ecs::components::ui::Dropdown::position, rtp::ecs::components::ui::Dropdown::size, rtp::Vec2< T >::x, and rtp::Vec2< T >::y.
Referenced by handleMouseClick().
isMouseOverSlider()
bool rtp::client::UISystem::isMouseOverSlider (const ecs::components::ui::Slider & slider, const sf::Vector2i & mousePos) private
Definition at line 270 of file UISystem.cpp.
References rtp::ecs::components::ui::Slider::position, rtp::ecs::components::ui::Slider::size, rtp::Vec2< T >::x, and rtp::Vec2< T >::y.
Referenced by handleMouseClick().
isMouseOverTextInput()
bool rtp::client::UISystem::isMouseOverTextInput (const ecs::components::ui::TextInput & input, const sf::Vector2i & mousePos) const private
Definition at line 343 of file UISystem.cpp.
References rtp::ecs::components::ui::TextInput::position, rtp::ecs::components::ui::TextInput::size, rtp::Vec2< T >::x, and rtp::Vec2< T >::y.
Referenced by focusTextInputAt(), and handleMouseClick().
playClickSound()
void rtp::client::UISystem::playClickSound () private
Definition at line 589 of file UISystem.cpp.
References _registry, rtp::log::error(), rtp::log::info(), rtp::ecs::components::audio::SoundEvent::pitch, rtp::ecs::components::audio::SoundEvent::soundPath, and rtp::ecs::components::audio::SoundEvent::volume.
Referenced by handleMouseClick().
renderGamepadCursor()
void rtp::client::UISystem::renderGamepadCursor (sf::RenderWindow & window)
Definition at line 568 of file UISystem.cpp.
References _gamepadCursorPos, _gamepadMode, and _settings.
update()
void rtp::client::UISystem::update (float deltaTime) override virtual
Update system logic for one frame.
Parameters
registry The entity registry to operate on
deltaTime Time elapsed since last update in seconds
Implements rtp::ecs::ISystem.
Definition at line 17 of file UISystem.cpp.
References _gamepadCursorPos, _gamepadMode, _registry, _window, handleGamepadInput(), handleMouseClick(), handleMouseMove(), and updateGamepadCursor().
updateGamepadCursor()
void rtp::client::UISystem::updateGamepadCursor (float dt) private
Definition at line 498 of file UISystem.cpp.
References _gamepadCursorPos, _gamepadMode, _settings, and _window.
Referenced by update().
updateSliderValue()
void rtp::client::UISystem::updateSliderValue (ecs::components::ui::Slider & slider, const sf::Vector2i & mousePos) private
Definition at line 302 of file UISystem.cpp.
References rtp::ecs::components::ui::Slider::currentValue, rtp::ecs::components::ui::Slider::maxValue, rtp::ecs::components::ui::Slider::minValue, rtp::ecs::components::ui::Slider::onChange, rtp::ecs::components::ui::Slider::position, rtp::ecs::components::ui::Slider::size, and rtp::Vec2< T >::x.
Referenced by handleMouseClick().
Member Data Documentation
_gamepadButtonClock
sf::Clock rtp::client::UISystem::_gamepadButtonClock private
Definition at line 87 of file UISystem.hpp.
_gamepadCursorPos
sf::Vector2f rtp::client::UISystem::_gamepadCursorPos private
Definition at line 85 of file UISystem.hpp.
Referenced by UISystem(), handleGamepadInput(), renderGamepadCursor(), update(), and updateGamepadCursor().
_gamepadMode
bool rtp::client::UISystem::_gamepadMode {false} private
Definition at line 86 of file UISystem.hpp.
Referenced by handleGamepadInput(), renderGamepadCursor(), update(), and updateGamepadCursor().
_registry
ecs::Registry& rtp::client::UISystem::_registry private
Definition at line 81 of file UISystem.hpp.
Referenced by UISystem(), clearAllTextInputFocus(), focusTextInputAt(), handleKeyPressed(), handleMouseClick(), handleMouseMove(), handleTextEntered(), playClickSound(), and update().
_settings
Settings& rtp::client::UISystem::_settings private
Definition at line 83 of file UISystem.hpp.
Referenced by UISystem(), handleGamepadInput(), renderGamepadCursor(), and updateGamepadCursor().
_window
sf::RenderWindow& rtp::client::UISystem::_window private
Definition at line 82 of file UISystem.hpp.
Referenced by UISystem(), update(), and updateGamepadCursor().
The documentation for this class was generated from the following files:
client/include/Systems/UISystem.hpp
client/src/Systems/UISystem.cpp