Air-Trap: rtp::server::PlayerShootSystem Class Reference
rtp::server::PlayerShootSystem Class Reference
Spawns bullets from player input on the server.
#include <PlayerShootSystem.hpp>
Public Member Functions
PlayerShootSystem (ecs::Registry &registry, RoomSystem &roomSystem, NetworkSyncSystem &networkSync)
Constructor for PlayerShootSystem.
void update (float dt) override
Update player shoot system logic for one frame.
Public Member Functions inherited from rtp::ecs::ISystem
virtual ~ISystem () noexcept=default
Private Member Functions
void spawnBullet (ecs::Entity owner, const ecs::components::Transform &tf, const ecs::components::RoomId &roomId, bool doubleFire=false)
Spawn a bullet entity based on the player's transform and room ID.
void spawnChargedBullet (ecs::Entity owner, const ecs::components::Transform &tf, const ecs::components::RoomId &roomId, float chargeRatio, bool doubleFire=false)
Spawn a charged bullet based on the player's transform and room ID.
void sendAmmoUpdate (uint32_t netId, const ecs::components::Ammo &ammo)
Send an ammo update to the client for a specific network ID.
void spawnDebugPowerup (const Vec2f &position, uint32_t roomId, int dropRoll)
Spawn a debug powerup for testing (triggered by P key).
Private Attributes
ecs::Registry & _registry
Reference to the entity registry.
RoomSystem & _roomSystem
Reference to the RoomSystem.
NetworkSyncSystem & _networkSync
Reference to the NetworkSyncSystem.
float _bulletSpeed = 500.0f
Speed of the spawned bullets.
float _chargedBulletSpeed = 280.0f
Speed of the charged bullets.
float _spawnOffsetX = 20.0f
X offset for bullet spawn position.
std::unordered_map< uint32_t, float > _beamTickTimers
Detailed Description
Spawns bullets from player input on the server.
Definition at line 40 of file PlayerShootSystem.hpp.
Constructor & Destructor Documentation
PlayerShootSystem()
rtp::server::PlayerShootSystem::PlayerShootSystem (ecs::Registry & registry, RoomSystem & roomSystem, NetworkSyncSystem & networkSync)
Constructor for PlayerShootSystem.
Parameters
registry Reference to the entity registry
roomSystem Reference to the RoomSystem
networkSync Reference to the NetworkSyncSystem
Definition at line 46 of file PlayerShootSystem.cpp.
References _networkSync, _registry, and _roomSystem.
Member Function Documentation
sendAmmoUpdate()
void rtp::server::PlayerShootSystem::sendAmmoUpdate (uint32_t netId, const ecs::components::Ammo & ammo) private
Send an ammo update to the client for a specific network ID.
Parameters
netId Network ID of the entity
ammo Ammo component to send
Definition at line 964 of file PlayerShootSystem.cpp.
References _networkSync, rtp::net::AmmoUpdate, rtp::net::AmmoUpdatePayload::cooldownRemaining, rtp::ecs::components::Ammo::current, rtp::net::AmmoUpdatePayload::current, rtp::ecs::components::Ammo::isReloading, rtp::net::AmmoUpdatePayload::isReloading, rtp::ecs::components::Ammo::max, rtp::net::AmmoUpdatePayload::max, rtp::ecs::components::Ammo::reloadCooldown, rtp::ecs::components::Ammo::reloadTimer, and rtp::net::TCP.
Referenced by update().
spawnBullet()
void rtp::server::PlayerShootSystem::spawnBullet (ecs::Entity owner, const ecs::components::Transform & tf, const ecs::components::RoomId & roomId, bool doubleFire = false) private
Spawn a bullet entity based on the player's transform and room ID.
Parameters
tf Transform component of the player
roomId RoomId component of the player
doubleFire Whether to spawn two bullets (double fire power-up)
Definition at line 492 of file PlayerShootSystem.cpp.
References _bulletSpeed, _networkSync, _registry, _roomSystem, _spawnOffsetX, rtp::net::Bullet, rtp::net::EntitySpawn, rtp::log::error(), rtp::ecs::components::RoomId::id, rtp::ecs::Entity::index(), rtp::server::Room::InGame, rtp::ecs::components::Boomerang::maxDistance, rtp::ecs::components::Boomerang::ownerIndex, rtp::ecs::components::Transform::position, rtp::ecs::components::Homing::range, rtp::ecs::components::Boomerang::returning, rtp::ecs::components::Boomerang::startPos, rtp::ecs::components::Homing::steering, rtp::net::TCP, rtp::Vec2< T >::x, and rtp::Vec2< T >::y.
Referenced by update().
spawnChargedBullet()
void rtp::server::PlayerShootSystem::spawnChargedBullet (ecs::Entity owner, const ecs::components::Transform & tf, const ecs::components::RoomId & roomId, float chargeRatio, bool doubleFire = false) private
Spawn a charged bullet based on the player's transform and room ID.
Parameters
tf Transform component of the player
roomId RoomId component of the player
chargeRatio Charge ratio in [0, 1]
doubleFire Whether to spawn two bullets (double fire power-up)
Definition at line 744 of file PlayerShootSystem.cpp.
References _chargedBulletSpeed, _networkSync, _registry, _roomSystem, _spawnOffsetX, rtp::net::ChargedBullet, rtp::net::EntitySpawn, rtp::log::error(), rtp::ecs::components::RoomId::id, rtp::ecs::Entity::index(), rtp::server::Room::InGame, rtp::ecs::components::Boomerang::maxDistance, rtp::ecs::components::Boomerang::ownerIndex, rtp::ecs::components::Transform::position, rtp::ecs::components::Homing::range, rtp::ecs::components::Boomerang::returning, rtp::ecs::components::Boomerang::startPos, rtp::ecs::components::Homing::steering, rtp::net::TCP, rtp::net::EntitySpawnPayload::weaponKind, rtp::Vec2< T >::x, and rtp::Vec2< T >::y.
Referenced by update().
spawnDebugPowerup()
void rtp::server::PlayerShootSystem::spawnDebugPowerup (const Vec2f & position, uint32_t roomId, int dropRoll) private
Spawn a debug powerup for testing (triggered by P key).
Parameters
position Position to spawn the powerup
roomId Room ID
dropRoll Random roll to determine powerup type (0-29)
Definition at line 978 of file PlayerShootSystem.cpp.
References _networkSync, _registry, _roomSystem, rtp::ecs::components::DoubleFire, rtp::net::EntitySpawn, rtp::log::error(), rtp::ecs::components::Heal, rtp::ecs::Entity::index(), rtp::net::PowerupDoubleFire, rtp::net::PowerupHeal, rtp::net::PowerupShield, rtp::ecs::components::Shield, rtp::net::TCP, rtp::Vec2< T >::x, and rtp::Vec2< T >::y.
Referenced by update().
update()
void rtp::server::PlayerShootSystem::update (float dt) override virtual
Update player shoot system logic for one frame.
Parameters
dt Time elapsed since last update in seconds
Implements rtp::ecs::ISystem.
Definition at line 53 of file PlayerShootSystem.cpp.
References _beamTickTimers, _networkSync, _registry, _roomSystem, rtp::net::BeamStatePayload::active, rtp::ecs::components::Beam, rtp::net::BeamState, rtp::net::EntityDeath, rtp::ecs::Entity::index(), rtp::log::info(), rtp::net::BeamStatePayload::length, rtp::net::EntityDeathPayload::netId, rtp::ecs::NullEntity, rtp::net::BeamStatePayload::offsetY, rtp::net::BeamStatePayload::ownerNetId, rtp::net::Player, rtp::net::EntityDeathPayload::position, rtp::net::ScoreUpdate, sendAmmoUpdate(), spawnBullet(), spawnChargedBullet(), spawnDebugPowerup(), rtp::net::TCP, rtp::net::BeamStatePayload::timeRemaining, rtp::net::EntityDeathPayload::type, rtp::Vec2< T >::x, and rtp::Vec2< T >::y.
Member Data Documentation
_beamTickTimers
std::unordered_map<uint32_t, float> rtp::server::PlayerShootSystem::_beamTickTimers private
Definition at line 108 of file PlayerShootSystem.hpp.
Referenced by update().
_bulletSpeed
float rtp::server::PlayerShootSystem::_bulletSpeed = 500.0f private
Speed of the spawned bullets.
Definition at line 103 of file PlayerShootSystem.hpp.
Referenced by spawnBullet().
_chargedBulletSpeed
float rtp::server::PlayerShootSystem::_chargedBulletSpeed = 280.0f private
Speed of the charged bullets.
Definition at line 104 of file PlayerShootSystem.hpp.
Referenced by spawnChargedBullet().
_networkSync
NetworkSyncSystem& rtp::server::PlayerShootSystem::_networkSync private
Reference to the NetworkSyncSystem.
Definition at line 101 of file PlayerShootSystem.hpp.
Referenced by PlayerShootSystem(), sendAmmoUpdate(), spawnBullet(), spawnChargedBullet(), spawnDebugPowerup(), and update().
_registry
ecs::Registry& rtp::server::PlayerShootSystem::_registry private
Reference to the entity registry.
Definition at line 99 of file PlayerShootSystem.hpp.
Referenced by PlayerShootSystem(), spawnBullet(), spawnChargedBullet(), spawnDebugPowerup(), and update().
_roomSystem
RoomSystem& rtp::server::PlayerShootSystem::_roomSystem private
Reference to the RoomSystem.
Definition at line 100 of file PlayerShootSystem.hpp.
Referenced by PlayerShootSystem(), spawnBullet(), spawnChargedBullet(), spawnDebugPowerup(), and update().
_spawnOffsetX
float rtp::server::PlayerShootSystem::_spawnOffsetX = 20.0f private
X offset for bullet spawn position.
Definition at line 105 of file PlayerShootSystem.hpp.
Referenced by spawnBullet(), and spawnChargedBullet().
The documentation for this class was generated from the following files:
server/include/Systems/PlayerShootSystem.hpp
server/src/Systems/PlayerShootSystem.cpp