Air-Trap: rtp::sys::DynamicLibrary Class Reference
rtp::sys::DynamicLibrary Class Reference final
Represents a dynamically loaded library.
#include <DynamicLibrary.hpp>
Public Member Functions
DynamicLibrary (void *handle) noexcept
Construct a DynamicLibrary with the given handle.
~DynamicLibrary () noexcept
Destructor.
DynamicLibrary (DynamicLibrary &&other) noexcept
DynamicLibrary & operator= (DynamicLibrary &&other) noexcept
DynamicLibrary (const DynamicLibrary &)=delete
DynamicLibrary & operator= (const DynamicLibrary &)=delete
template<typename T>
auto get (std::string_view name) const -> std::expected< T, rtp::Error >
Get a symbol from the dynamic library.
Private Member Functions
auto getSymbolAddress (std::string_view name) const -> std::expected< void *, rtp::Error >
Get the address of a symbol from the dynamic library.
Private Attributes
void * _handle {nullptr}
The handle to the dynamic library.
Detailed Description
Represents a dynamically loaded library.
Provides methods to retrieve symbols from the library.
Definition at line 56 of file DynamicLibrary.hpp.
Constructor & Destructor Documentation
DynamicLibrary() [1/3]
rtp::sys::DynamicLibrary::DynamicLibrary (void * handle) explicit noexcept
Construct a DynamicLibrary with the given handle.
Parameters
handle The handle to the dynamic library.
Note
expect handle to be a valid pointer to an handler.
Definition at line 52 of file DynamicLibrary.cpp.
References _handle.
Referenced by DynamicLibrary(), DynamicLibrary(), operator=(), and operator=().
~DynamicLibrary()
rtp::sys::DynamicLibrary::~DynamicLibrary () noexcept
Destructor.
Closes the dynamic library.
Definition at line 56 of file DynamicLibrary.cpp.
References _handle, rtp::sys::impl::LibraryBackend::close(), and rtp::log::warning().
DynamicLibrary() [2/3]
rtp::sys::DynamicLibrary::DynamicLibrary (DynamicLibrary && other) noexcept
Definition at line 67 of file DynamicLibrary.cpp.
References DynamicLibrary(), and _handle.
DynamicLibrary() [3/3]
rtp::sys::DynamicLibrary::DynamicLibrary (const DynamicLibrary &) delete
References DynamicLibrary().
Member Function Documentation
get()
template<typename T> auto rtp::sys::DynamicLibrary::get (std::string_view name) const->std::expected< T, rtp::Error > nodiscard
Get a symbol from the dynamic library.
Template Parameters
T The expected type of the symbol.
Parameters
name The name of the symbol to retrieve.
Returns
std::expected<T, rtp::Error>
getSymbolAddress()
auto rtp::sys::DynamicLibrary::getSymbolAddress (std::string_view name) const->std::expected< void *, rtp::Error > nodiscard private
Get the address of a symbol from the dynamic library.
Parameters
name The name of the symbol to retrieve.
Returns
std::expected<void *, rtp::Error>
Definition at line 90 of file DynamicLibrary.cpp.
References _handle, and rtp::sys::impl::LibraryBackend::getSymbol().
operator=() [1/2]
DynamicLibrary & rtp::sys::DynamicLibrary::operator= (const DynamicLibrary &) delete
References DynamicLibrary().
operator=() [2/2]
DynamicLibrary & rtp::sys::DynamicLibrary::operator= (DynamicLibrary && other) noexcept
Definition at line 73 of file DynamicLibrary.cpp.
References DynamicLibrary(), _handle, rtp::sys::impl::LibraryBackend::close(), and rtp::log::warning().
Member Data Documentation
_handle
void* rtp::sys::DynamicLibrary::_handle {nullptr} private
The handle to the dynamic library.
Definition at line 89 of file DynamicLibrary.hpp.
Referenced by DynamicLibrary(), DynamicLibrary(), ~DynamicLibrary(), getSymbolAddress(), and operator=().
The documentation for this class was generated from the following files:
common/include/RType/System/DynamicLibrary.hpp
common/src/System/DynamicLibrary.cpp