Air-Trap: rtp::client::scenes::GamepadSettingsScene Class Reference
rtp::client::scenes::GamepadSettingsScene Class Reference
Scene for configuring gamepad settings.
#include <GamepadSettingsScene.hpp>
Public Types
using ChangeStateFn = std::function<void(GameState)>
Public Member Functions
GamepadSettingsScene (ecs::Registry &UiRegistry, Settings &settings, TranslationManager &translationManager, NetworkSyncSystem &network, graphics::UiFactory &uiFactory, std::function< void(GameState)> changeState)
void onEnter () override
Called when the scene is entered.
void onExit () override
Called when the scene is exited.
void handleEvent (const sf::Event &event) override
Handle an incoming event.
void update (float dt) override
Update the scene state.
Public Member Functions inherited from rtp::client::interfaces::IScene
virtual ~IScene (void)=default
Private Member Functions
void refreshButtonLabel (GamepadAction action)
std::string getButtonName (unsigned int button) const
Private Attributes
ecs::Registry & _uiRegistry
Settings & _settings
TranslationManager & _translationManager
NetworkSyncSystem & _network
graphics::UiFactory & _uiFactory
ChangeStateFn _changeState
bool _isWaitingForButton {false}
GamepadAction _actionToRebind
std::unordered_map< GamepadAction, ecs::Entity > _actionToButton
Detailed Description
Scene for configuring gamepad settings.
Definition at line 36 of file GamepadSettingsScene.hpp.
Member Typedef Documentation
ChangeStateFn
using rtp::client::scenes::GamepadSettingsScene::ChangeStateFn = std::function<void(GameState)>
Definition at line 46 of file GamepadSettingsScene.hpp.
Constructor & Destructor Documentation
GamepadSettingsScene()
rtp::client::scenes::GamepadSettingsScene::GamepadSettingsScene (ecs::Registry & UiRegistry, Settings & settings, TranslationManager & translationManager, NetworkSyncSystem & network, graphics::UiFactory & uiFactory, std::function< void(GameState)> changeState)
Definition at line 18 of file GamepadSettingsScene.cpp.
References _changeState, _network, _settings, _translationManager, _uiFactory, and _uiRegistry.
Member Function Documentation
getButtonName()
std::string rtp::client::scenes::GamepadSettingsScene::getButtonName (unsigned int button) const private
Definition at line 300 of file GamepadSettingsScene.cpp.
Referenced by handleEvent(), onEnter(), and refreshButtonLabel().
handleEvent()
void rtp::client::scenes::GamepadSettingsScene::handleEvent (const sf::Event &) override virtual
Handle an incoming event.
Parameters
event The event to handle.
Implements rtp::client::interfaces::IScene.
Definition at line 202 of file GamepadSettingsScene.cpp.
References _actionToRebind, _isWaitingForButton, _settings, getButtonName(), rtp::log::info(), rtp::client::scenes::Pause, refreshButtonLabel(), rtp::client::scenes::Reload, and rtp::client::scenes::Shoot.
onEnter()
void rtp::client::scenes::GamepadSettingsScene::onEnter () override virtual
Called when the scene is entered.
Note
Used for initializing scene-specific resources.
Implements rtp::client::interfaces::IScene.
Definition at line 33 of file GamepadSettingsScene.cpp.
References _actionToButton, _actionToRebind, _changeState, _isWaitingForButton, _settings, _translationManager, _uiFactory, _uiRegistry, getButtonName(), rtp::log::info(), rtp::client::scenes::Pause, refreshButtonLabel(), rtp::client::scenes::Reload, rtp::client::Settings, and rtp::client::scenes::Shoot.
onExit()
void rtp::client::scenes::GamepadSettingsScene::onExit () override virtual
Called when the scene is exited.
Note
Used for cleaning up scene-specific resources.
Implements rtp::client::interfaces::IScene.
Definition at line 197 of file GamepadSettingsScene.cpp.
References _isWaitingForButton.
refreshButtonLabel()
void rtp::client::scenes::GamepadSettingsScene::refreshButtonLabel (GamepadAction action) private
Definition at line 259 of file GamepadSettingsScene.cpp.
References _actionToButton, _isWaitingForButton, _settings, _uiRegistry, rtp::log::error(), getButtonName(), rtp::client::scenes::Pause, rtp::client::scenes::Reload, rtp::client::scenes::Shoot, rtp::ecs::components::ui::Button::text, and rtp::log::warning().
Referenced by handleEvent(), and onEnter().
update()
void rtp::client::scenes::GamepadSettingsScene::update (float dt) override virtual
Update the scene state.
Parameters
dt Time delta since the last update.
Implements rtp::client::interfaces::IScene.
Definition at line 250 of file GamepadSettingsScene.cpp.
Member Data Documentation
_actionToButton
std::unordered_map<GamepadAction, ecs::Entity> rtp::client::scenes::GamepadSettingsScene::_actionToButton private
Definition at line 66 of file GamepadSettingsScene.hpp.
Referenced by onEnter(), and refreshButtonLabel().
_actionToRebind
GamepadAction rtp::client::scenes::GamepadSettingsScene::_actionToRebind private
Definition at line 65 of file GamepadSettingsScene.hpp.
Referenced by handleEvent(), and onEnter().
_changeState
ChangeStateFn rtp::client::scenes::GamepadSettingsScene::_changeState private
Definition at line 62 of file GamepadSettingsScene.hpp.
Referenced by GamepadSettingsScene(), and onEnter().
_isWaitingForButton
bool rtp::client::scenes::GamepadSettingsScene::_isWaitingForButton {false} private
Definition at line 64 of file GamepadSettingsScene.hpp.
Referenced by handleEvent(), onEnter(), onExit(), and refreshButtonLabel().
_network
NetworkSyncSystem& rtp::client::scenes::GamepadSettingsScene::_network private
Definition at line 60 of file GamepadSettingsScene.hpp.
Referenced by GamepadSettingsScene().
_settings
Settings& rtp::client::scenes::GamepadSettingsScene::_settings private
Definition at line 58 of file GamepadSettingsScene.hpp.
Referenced by GamepadSettingsScene(), handleEvent(), onEnter(), and refreshButtonLabel().
_translationManager
TranslationManager& rtp::client::scenes::GamepadSettingsScene::_translationManager private
Definition at line 59 of file GamepadSettingsScene.hpp.
Referenced by GamepadSettingsScene(), and onEnter().
_uiFactory
graphics::UiFactory& rtp::client::scenes::GamepadSettingsScene::_uiFactory private
Definition at line 61 of file GamepadSettingsScene.hpp.
Referenced by GamepadSettingsScene(), and onEnter().
_uiRegistry
ecs::Registry& rtp::client::scenes::GamepadSettingsScene::_uiRegistry private
Definition at line 57 of file GamepadSettingsScene.hpp.
Referenced by GamepadSettingsScene(), onEnter(), and refreshButtonLabel().
The documentation for this class was generated from the following files:
client/include/Scenes/GamepadSettingsScene.hpp
client/src/Scenes/GamepadSettingsScene.cpp