Air-Trap: rtp::client::EntityBuilder Class Reference
rtp::client::EntityBuilder Class Reference
#include <EntityBuilder.hpp>
Public Member Functions
EntityBuilder (ecs::Registry &registry)
auto spawn (const EntityTemplate &t) -> std::expected< ecs::Entity, Error >
void kill (ecs::Entity entity)
void update (ecs::Entity entity, const EntityTemplate &t)
Private Attributes
ecs::Registry & _registry
Detailed Description
Definition at line 700 of file EntityBuilder.hpp.
Constructor & Destructor Documentation
EntityBuilder()
rtp::client::EntityBuilder::EntityBuilder (ecs::Registry & registry) explicit
Definition at line 15 of file EntityBuilder.cpp.
References _registry.
Member Function Documentation
kill()
void rtp::client::EntityBuilder::kill (ecs::Entity entity)
Definition at line 150 of file EntityBuilder.cpp.
References _registry.
spawn()
auto rtp::client::EntityBuilder::spawn (const EntityTemplate & t) ->std::expected< ecs::Entity, Error > nodiscard
Definition at line 20 of file EntityBuilder.cpp.
References _registry, rtp::log::debug(), rtp::client::SpriteCustomizer::getInstance(), and rtp::log::info().
update()
void rtp::client::EntityBuilder::update (ecs::Entity entity, const EntityTemplate & t)
Definition at line 155 of file EntityBuilder.cpp.
References _registry, rtp::client::EntityTemplate::animation, rtp::client::EntityTemplate::position, rtp::client::EntityTemplate::rotation, rtp::client::EntityTemplate::scale, rtp::client::EntityTemplate::sprite, rtp::client::EntityTemplate::velocity, rtp::client::EntityTemplate::withAnimation, and rtp::client::EntityTemplate::withVelocity.
Member Data Documentation
_registry
ecs::Registry& rtp::client::EntityBuilder::_registry private
Definition at line 713 of file EntityBuilder.hpp.
Referenced by EntityBuilder(), kill(), spawn(), and update().
The documentation for this class was generated from the following files:
client/include/Game/EntityBuilder.hpp
client/src/Game/EntityBuilder.cpp