Air-Trap: rtp::server::PlayerSystem Class Reference
rtp::server::PlayerSystem Class Reference
System to handle player-related operations on the server side.
#include <PlayerSystem.hpp>
Public Member Functions
PlayerSystem (ServerNetwork &network, ecs::Registry &registry)
Constructor for PlayerSystem.
void update (float dt) override
Update system logic for one frame.
PlayerPtr createPlayer (uint32_t sessionId, const std::string &username)
Create a new player for the given session ID.
uint32_t removePlayer (uint32_t sessionId)
Remove a player by their session ID.
void updatePlayerUsername (uint32_t sessionId, const std::string &username)
Update the username of a player.
PlayerPtr getPlayer (uint32_t sessionId) const
Get a player by their session ID.
PlayerPtr getPlayerByUsername (const std::string &username) const
Get a player by their username.
Public Member Functions inherited from rtp::ecs::ISystem
virtual ~ISystem () noexcept=default
Private Attributes
ServerNetwork & _network
Reference to the server network manager.
ecs::Registry & _registry
Reference to the entity registry.
std::map< uint32_t, PlayerPtr > _players
Map of session ID to Player instances.
Detailed Description
System to handle player-related operations on the server side.
Definition at line 27 of file PlayerSystem.hpp.
Constructor & Destructor Documentation
PlayerSystem()
rtp::server::PlayerSystem::PlayerSystem (ServerNetwork & network, ecs::Registry & registry)
Constructor for PlayerSystem.
Parameters
network Reference to the server network manager
registry Reference to the entity registry
Definition at line 15 of file PlayerSystem.cpp.
References _network, and _registry.
Member Function Documentation
createPlayer()
PlayerPtr rtp::server::PlayerSystem::createPlayer (uint32_t sessionId, const std::string & username)
Create a new player for the given session ID.
Parameters
sessionId ID of the network session
username Username of the player
Definition at line 23 of file PlayerSystem.cpp.
References _players, rtp::log::info(), and rtp::log::warning().
getPlayer()
PlayerPtr rtp::server::PlayerSystem::getPlayer (uint32_t sessionId) const
Get a player by their session ID.
Parameters
sessionId ID of the network session
Returns
Shared pointer to the Player, or nullptr if not found
Definition at line 58 of file PlayerSystem.cpp.
References _players.
getPlayerByUsername()
PlayerPtr rtp::server::PlayerSystem::getPlayerByUsername (const std::string & username) const
Get a player by their username.
Parameters
username Username to look up
Returns
Shared pointer to the Player, or nullptr if not found
Definition at line 67 of file PlayerSystem.cpp.
References _players.
removePlayer()
uint32_t rtp::server::PlayerSystem::removePlayer (uint32_t sessionId)
Remove a player by their session ID.
Parameters
sessionId ID of the network session
Returns
The entity ID associated with the removed player, or 0 if not found
Definition at line 36 of file PlayerSystem.cpp.
References _players, and rtp::log::info().
update()
void rtp::server::PlayerSystem::update (float dt) override virtual
Update system logic for one frame.
Parameters
dt Time elapsed since last update in seconds
Note
Currently not used
Implements rtp::ecs::ISystem.
Definition at line 18 of file PlayerSystem.cpp.
updatePlayerUsername()
void rtp::server::PlayerSystem::updatePlayerUsername (uint32_t sessionId, const std::string & username)
Update the username of a player.
Parameters
sessionId ID of the network session
username New username of the player
Definition at line 49 of file PlayerSystem.cpp.
References _players, and rtp::log::info().
Member Data Documentation
_network
ServerNetwork& rtp::server::PlayerSystem::_network private
Reference to the server network manager.
Definition at line 79 of file PlayerSystem.hpp.
Referenced by PlayerSystem().
_players
std::map<uint32_t, PlayerPtr> rtp::server::PlayerSystem::_players private
Map of session ID to Player instances.
Definition at line 83 of file PlayerSystem.hpp.
Referenced by createPlayer(), getPlayer(), getPlayerByUsername(), removePlayer(), and updatePlayerUsername().
_registry
ecs::Registry& rtp::server::PlayerSystem::_registry private
Reference to the entity registry.
Definition at line 80 of file PlayerSystem.hpp.
Referenced by PlayerSystem().
The documentation for this class was generated from the following files:
server/include/Systems/PlayerSystem.hpp
server/src/Systems/PlayerSystem.cpp