Air-Trap: rtp::server::CollisionSystem Class Reference
rtp::server::CollisionSystem Class Reference
#include <CollisionSystem.hpp>
Public Member Functions
CollisionSystem (ecs::Registry &registry, RoomSystem &roomSystem, NetworkSyncSystem &networkSync)
Constructor for CollisionSystem.
void update (float dt) override
Update system logic for one frame.
void setInvincible (bool enabled)
Set invincibility mode for all players.
bool isInvincible () const
Check if invincibility mode is enabled.
Public Member Functions inherited from rtp::ecs::ISystem
virtual ~ISystem () noexcept=default
Private Member Functions
bool overlaps (const ecs::components::Transform &a, const ecs::components::BoundingBox &ab, const ecs::components::Transform &b, const ecs::components::BoundingBox &bb) const
Check if two entities overlap based on their transforms and bounding boxes.
void despawn (const ecs::Entity &entity, uint32_t roomId)
Handle collision between two entities.
void spawnPowerup (const Vec2f &position, uint32_t roomId, int dropRoll)
Spawn a power-up at given position.
Private Attributes
ecs::Registry & _registry
Reference to the ECS registry.
RoomSystem & _roomSystem
Reference to the RoomSystem.
NetworkSyncSystem & _networkSync
Reference to the NetworkSyncSystem.
bool _invincibleMode = false
Debug: players are invincible.
Detailed Description
Definition at line 34 of file CollisionSystem.hpp.
Constructor & Destructor Documentation
CollisionSystem()
rtp::server::CollisionSystem::CollisionSystem (ecs::Registry & registry, RoomSystem & roomSystem, NetworkSyncSystem & networkSync)
Constructor for CollisionSystem.
Parameters
registry Reference to the ECS registry
roomSystem Reference to the RoomSystem
networkSync Reference to the NetworkSyncSystem
Definition at line 40 of file CollisionSystem.cpp.
References _networkSync, _registry, and _roomSystem.
Member Function Documentation
despawn()
void rtp::server::CollisionSystem::despawn (const ecs::Entity & entity, uint32_t roomId) private
Handle collision between two entities.
Parameters
entityA First entity involved in the collision
entityB Second entity involved in the collision
Definition at line 640 of file CollisionSystem.cpp.
References _networkSync, _registry, _roomSystem, rtp::log::debug(), rtp::net::EntityDeath, rtp::ecs::Entity::index(), rtp::net::EntityDeathPayload::netId, rtp::net::EntityDeathPayload::position, rtp::net::TCP, and rtp::net::EntityDeathPayload::type.
Referenced by update().
isInvincible()
bool rtp::server::CollisionSystem::isInvincible () const inline
Check if invincibility mode is enabled.
Returns
true if invincibility is enabled
Definition at line 62 of file CollisionSystem.hpp.
References _invincibleMode.
overlaps()
bool rtp::server::CollisionSystem::overlaps (const ecs::components::Transform & a, const ecs::components::BoundingBox & ab, const ecs::components::Transform & b, const ecs::components::BoundingBox & bb) const private
Check if two entities overlap based on their transforms and bounding boxes.
Parameters
a Transform of the first entity
ab BoundingBox of the first entity
b Transform of the second entity
bb BoundingBox of the second entity
Returns
true if the entities overlap, false otherwise
Definition at line 622 of file CollisionSystem.cpp.
References rtp::ecs::components::BoundingBox::height, rtp::ecs::components::Transform::position, rtp::ecs::components::BoundingBox::width, rtp::Vec2< T >::x, and rtp::Vec2< T >::y.
Referenced by update().
setInvincible()
void rtp::server::CollisionSystem::setInvincible (bool enabled) inline
Set invincibility mode for all players.
Parameters
enabled Whether invincibility is enabled
Definition at line 56 of file CollisionSystem.hpp.
References _invincibleMode.
spawnPowerup()
void rtp::server::CollisionSystem::spawnPowerup (const Vec2f & position, uint32_t roomId, int dropRoll) private
Spawn a power-up at given position.
Parameters
position Position to spawn the power-up
roomId Room ID
dropRoll Random value to determine power-up type
Definition at line 695 of file CollisionSystem.cpp.
References _networkSync, _registry, _roomSystem, rtp::ecs::components::DoubleFire, rtp::net::EntitySpawn, rtp::log::error(), rtp::ecs::components::Heal, rtp::log::info(), rtp::net::EntitySpawnPayload::netId, rtp::net::EntitySpawnPayload::posX, rtp::net::EntitySpawnPayload::posY, rtp::net::PowerupDoubleFire, rtp::net::PowerupHeal, rtp::net::PowerupShield, rtp::ecs::components::Shield, rtp::net::TCP, rtp::net::EntitySpawnPayload::type, rtp::Vec2< T >::x, and rtp::Vec2< T >::y.
Referenced by update().
update()
void rtp::server::CollisionSystem::update (float dt) override virtual
Update system logic for one frame.
Parameters
dt Time elapsed since last update in seconds
Implements rtp::ecs::ISystem.
Definition at line 49 of file CollisionSystem.cpp.
References _invincibleMode, _networkSync, _registry, _roomSystem, rtp::net::AmmoUpdate, rtp::net::GameOverPayload::bestPlayer, rtp::net::GameOverPayload::bestScore, rtp::net::Boss, rtp::net::Boss2, rtp::net::BossShield, rtp::net::Bullet, rtp::net::ChargedBullet, rtp::net::AmmoUpdatePayload::cooldownRemaining, rtp::net::AmmoUpdatePayload::current, despawn(), rtp::ecs::components::DoubleFire, rtp::net::EnemyBullet, rtp::net::GameOver, rtp::ecs::components::Heal, rtp::net::HealthUpdate, rtp::ecs::Entity::index(), rtp::log::info(), rtp::server::Room::InGame, rtp::net::AmmoUpdatePayload::isReloading, rtp::net::AmmoUpdatePayload::max, rtp::ecs::NullEntity, rtp::net::Obstacle, rtp::net::ObstacleSolid, overlaps(), rtp::net::Player, rtp::net::GameOverPayload::playerScore, rtp::net::PowerupDoubleFire, rtp::net::PowerupHeal, rtp::net::PowerupShield, rtp::net::PowerupSpeed, rtp::net::ScoreUpdate, rtp::net::Scout, rtp::ecs::components::Shield, spawnPowerup(), rtp::server::Room::Spectator, rtp::ecs::components::Speed, rtp::net::Tank, rtp::net::TCP, and rtp::log::warning().
Member Data Documentation
_invincibleMode
bool rtp::server::CollisionSystem::_invincibleMode = false private
Debug: players are invincible.
Definition at line 97 of file CollisionSystem.hpp.
Referenced by isInvincible(), setInvincible(), and update().
_networkSync
NetworkSyncSystem& rtp::server::CollisionSystem::_networkSync private
Reference to the NetworkSyncSystem.
Definition at line 96 of file CollisionSystem.hpp.
Referenced by CollisionSystem(), despawn(), spawnPowerup(), and update().
_registry
ecs::Registry& rtp::server::CollisionSystem::_registry private
Reference to the ECS registry.
Definition at line 94 of file CollisionSystem.hpp.
Referenced by CollisionSystem(), despawn(), spawnPowerup(), and update().
_roomSystem
RoomSystem& rtp::server::CollisionSystem::_roomSystem private
Reference to the RoomSystem.
Definition at line 95 of file CollisionSystem.hpp.
Referenced by CollisionSystem(), despawn(), spawnPowerup(), and update().
The documentation for this class was generated from the following files:
server/include/Systems/CollisionSystem.hpp
server/src/Systems/CollisionSystem.cpp