Air-Trap: rtp::server::GameManager Class Reference
rtp::server::GameManager Class Reference
Manages game state, rooms, and player interactions on the server side.
#include <GameManager.hpp>
Public Member Functions
GameManager (ServerNetwork &networkManager)
Constructor for GameManager.
~GameManager ()
Destructor for GameManager.
void gameLoop (void)
Main game loop.
void startGame (Room &room)
Start a game in the specified room.
Private Member Functions
void processNetworkEvents (void)
Process incoming network events with OpCode handling.
void handlePlayerConnect (uint32_t sessionId)
Handle a new player connection.
void handlePlayerDisconnect (uint32_t sessionId)
Handle a player disconnection.
void handlePlayerLoginAuth (uint32_t sessionId, const net::Packet &packet)
Handle player login with provided username if successful then join the lobby.
void handlePlayerRegisterAuth (uint32_t sessionId, const net::Packet &packet)
Handle player registration with provided username.
void handleListRooms (uint32_t sessionId)
Handle a request to list available rooms.
void handleCreateRoom (uint32_t sessionId, const net::Packet &packet)
Handle a generic incoming packet from a player.
void handleJoinRoom (uint32_t sessionId, const net::Packet &packet)
Handle a generic incoming packet from a player.
void handleLeaveRoom (uint32_t sessionId, const net::Packet &packet)
Handle a generic incoming packet from a player.
void handleSetReady (uint32_t sessionId, const net::Packet &packet)
Handle a generic incoming packet from a player.
void handleUpdateSelectedWeapon (uint32_t sessionId, const net::Packet &packet)
Handle an update to the selected weapon sent by client.
void handleRoomChatSended (uint32_t sessionId, const net::Packet &packet)
Handle a generic incoming packet from a player.
void handlePacket (uint32_t sessionId, const net::Packet &packet)
Handle an incoming packet from a player.
void handlePing (uint32_t sessionId, const net::Packet &packet)
bool handleChatCommand (PlayerPtr player, const std::string &message)
void sendChatToSession (uint32_t sessionId, const std::string &message)
void sendSystemMessageToRoom (uint32_t roomId, const std::string &message)
void sendEntitySpawnToSessions (const ecs::Entity &entity, const std::vector< uint32_t > &sessions)
void sendRoomEntitySpawnsToSession (uint32_t roomId, uint32_t sessionId)
Private Attributes
ServerNetwork & _networkManager
Reference to the ServerNetwork instance.
ecs::Registry _registry
ECS Registry for managing entities and components.
std::unique_ptr< NetworkSyncSystem > _networkSyncSystem
Server network system for handling network-related ECS operations.
std::unique_ptr< MovementSystem > _movementSystem
Movement system for updating entity positions.
std::unique_ptr< AuthSystem > _authSystem
Authentication system for handling player logins.
std::unique_ptr< RoomSystem > _roomSystem
Room system for handling room management.
std::unique_ptr< PlayerSystem > _playerSystem
Player system for handling player-related operations.
std::unique_ptr< EntitySystem > _entitySystem
Entity system for handling entity-related operations.
std::unique_ptr< PlayerMouvementSystem > _playerMouvementSystem
Player movement system for handling player-specific movement logic.
std::unique_ptr< PlayerShootSystem > _playerShootSystem
Player shooting system for handling bullets.
std::unique_ptr< EnemyAISystem > _enemyAISystem
Enemy AI system for movement patterns.
std::unique_ptr< LevelSystem > _levelSystem
Level system for timed spawns.
std::unique_ptr< HomingSystem > _homingSystem
Homing system for tracker bullets.
std::unique_ptr< BoomerangSystem > _boomerangSystem
Boomerang system for boomerang projectiles.
std::unique_ptr< CollisionSystem > _collisionSystem
Collision system for pickups/obstacles.
std::unique_ptr< EnemyShootSystem > _enemyShootSystem
Enemy shooting system.
std::unique_ptr< BulletCleanupSystem > _bulletCleanupSystem
Bullet cleanup system.
uint32_t _serverTick = 0
Current server tick for synchronization.
std::mutex _mutex
Mutex for thread-safe operations.
bool _gamePaused = false
Global game pause flag.
float _gameSpeed = 1.0f
Global game speed multiplier.
Detailed Description
Manages game state, rooms, and player interactions on the server side.
Definition at line 72 of file GameManager.hpp.
Constructor & Destructor Documentation
GameManager()
rtp::server::GameManager::GameManager (ServerNetwork & networkManager)
Constructor for GameManager.
Parameters
networkManager Reference to the ServerNetwork instance
Definition at line 22 of file GameManager.cpp.
References _authSystem, _boomerangSystem, _bulletCleanupSystem, _collisionSystem, _enemyAISystem, _enemyShootSystem, _entitySystem, _homingSystem, _levelSystem, _movementSystem, _networkManager, _networkSyncSystem, _playerMouvementSystem, _playerShootSystem, _playerSystem, _registry, _roomSystem, rtp::log::error(), rtp::net::HealthUpdate, rtp::log::info(), rtp::server::LevelData::playerStart, rtp::net::ScoreUpdate, sendEntitySpawnToSessions(), and rtp::net::TCP.
~GameManager()
rtp::server::GameManager::~GameManager ()
Destructor for GameManager.
Definition at line 122 of file GameManager.cpp.
References rtp::log::info().
Member Function Documentation
gameLoop()
void rtp::server::GameManager::gameLoop (void)
Main game loop.
Note
Processes network events, updates game state, and manages rooms
Definition at line 127 of file GameManager.cpp.
References _boomerangSystem, _bulletCleanupSystem, _collisionSystem, _enemyAISystem, _enemyShootSystem, _gamePaused, _gameSpeed, _homingSystem, _levelSystem, _movementSystem, _playerMouvementSystem, _playerShootSystem, _roomSystem, _serverTick, and processNetworkEvents().
Referenced by main().
handleChatCommand()
bool rtp::server::GameManager::handleChatCommand (PlayerPtr player, const std::string & message) private
Definition at line 534 of file GameManager.cpp.
References _collisionSystem, _gamePaused, _gameSpeed, _networkManager, _playerSystem, _roomSystem, rtp::net::DebugModeUpdate, rtp::net::Kicked, rtp::net::LeaveRoom, sendChatToSession(), sendSystemMessageToRoom(), and rtp::net::TCP.
Referenced by handleRoomChatSended().
handleCreateRoom()
void rtp::server::GameManager::handleCreateRoom (uint32_t sessionId, const net::Packet & packet) private
Handle a generic incoming packet from a player.
Parameters
sessionId Unique identifier of the player sending the packet
packet Reference to the received Packet
Definition at line 339 of file GameManager.cpp.
References _mutex, _networkManager, _playerSystem, _roomSystem, rtp::net::CreateRoom, rtp::net::CreateRoomPayload::difficulty, rtp::net::CreateRoomPayload::duration, rtp::log::info(), rtp::net::CreateRoomPayload::levelId, rtp::net::CreateRoomPayload::maxPlayers, rtp::net::Private, rtp::net::CreateRoomPayload::roomName, rtp::net::CreateRoomPayload::roomType, rtp::net::CreateRoomPayload::seed, rtp::net::CreateRoomPayload::speed, and rtp::net::TCP.
Referenced by processNetworkEvents().
handleJoinRoom()
void rtp::server::GameManager::handleJoinRoom (uint32_t sessionId, const net::Packet & packet) private
Handle a generic incoming packet from a player.
Parameters
sessionId Unique identifier of the player sending the packet
packet Reference to the received Packet
Definition at line 386 of file GameManager.cpp.
References _mutex, _networkManager, _playerSystem, _roomSystem, rtp::server::Room::InGame, rtp::net::JoinRoomPayload::isSpectator, rtp::net::JoinRoomPayload::roomId, sendRoomEntitySpawnsToSession(), rtp::net::StartGame, and rtp::net::TCP.
Referenced by processNetworkEvents().
handleLeaveRoom()
void rtp::server::GameManager::handleLeaveRoom (uint32_t sessionId, const net::Packet & packet) private
Handle a generic incoming packet from a player.
Parameters
sessionId Unique identifier of the player sending the packet
packet Reference to the received Packet
Definition at line 415 of file GameManager.cpp.
References _mutex, _playerSystem, _roomSystem, and rtp::log::info().
Referenced by processNetworkEvents().
handleListRooms()
void rtp::server::GameManager::handleListRooms (uint32_t sessionId) private
Handle a request to list available rooms.
Parameters
sessionId Unique identifier of the player requesting the room list
packet Reference to the received Packet
Definition at line 334 of file GameManager.cpp.
References _roomSystem.
Referenced by processNetworkEvents().
handlePacket()
void rtp::server::GameManager::handlePacket (uint32_t sessionId, const net::Packet & packet) private
Handle an incoming packet from a player.
Parameters
sessionId Unique identifier of the player sending the packet
packet Reference to the received Packet
Definition at line 516 of file GameManager.cpp.
References _mutex, rtp::log::debug(), rtp::net::Packet::header, rtp::log::info(), rtp::net::LoginRequest, and rtp::net::Header::opCode.
Referenced by processNetworkEvents().
handlePing()
void rtp::server::GameManager::handlePing (uint32_t sessionId, const net::Packet & packet) private
Definition at line 523 of file GameManager.cpp.
References _networkManager, rtp::net::Pong, and rtp::net::UDP.
Referenced by processNetworkEvents().
handlePlayerConnect()
void rtp::server::GameManager::handlePlayerConnect (uint32_t sessionId) private
Handle a new player connection.
Parameters
sessionId Unique identifier of the connecting player
Definition at line 221 of file GameManager.cpp.
References rtp::log::info().
Referenced by processNetworkEvents().
handlePlayerDisconnect()
void rtp::server::GameManager::handlePlayerDisconnect (uint32_t sessionId) private
Handle a player disconnection.
Parameters
sessionId Unique identifier of the disconnecting player
Definition at line 226 of file GameManager.cpp.
References _mutex, _networkManager, _networkSyncSystem, _playerSystem, _registry, _roomSystem, rtp::net::Disconnect, rtp::net::EntityDeath, rtp::log::info(), rtp::net::EntityDeathPayload::netId, rtp::ecs::NullEntity, rtp::net::EntityDeathPayload::position, rtp::net::TCP, rtp::net::EntityDeathPayload::type, and rtp::net::UDP.
Referenced by processNetworkEvents().
handlePlayerLoginAuth()
void rtp::server::GameManager::handlePlayerLoginAuth (uint32_t sessionId, const net::Packet & packet) private
Handle player login with provided username if successful then join the lobby.
Parameters
sessionId Unique identifier of the player
username Player's username
Definition at line 292 of file GameManager.cpp.
References _authSystem, _mutex, _playerSystem, _roomSystem, rtp::log::error(), rtp::log::info(), and rtp::server::InLobby.
Referenced by processNetworkEvents().
handlePlayerRegisterAuth()
void rtp::server::GameManager::handlePlayerRegisterAuth (uint32_t sessionId, const net::Packet & packet) private
Handle player registration with provided username.
Parameters
sessionId Unique identifier of the player
username Player's username
Definition at line 315 of file GameManager.cpp.
References _authSystem, _mutex, _playerSystem, _roomSystem, rtp::log::error(), rtp::log::info(), and rtp::server::InLobby.
Referenced by processNetworkEvents().
handleRoomChatSended()
void rtp::server::GameManager::handleRoomChatSended (uint32_t sessionId, const net::Packet & packet) private
Handle a generic incoming packet from a player.
Parameters
sessionId Unique identifier of the player sending the packet
packet Reference to the received Packet
Definition at line 469 of file GameManager.cpp.
References _mutex, _networkManager, _playerSystem, _roomSystem, handleChatCommand(), rtp::net::RoomChatPayload::message, rtp::net::RoomChatReceivedPayload::message, rtp::net::RoomChatReceived, rtp::net::RoomChatReceivedPayload::sessionId, rtp::net::TCP, and rtp::net::RoomChatReceivedPayload::username.
Referenced by processNetworkEvents().
handleSetReady()
void rtp::server::GameManager::handleSetReady (uint32_t sessionId, const net::Packet & packet) private
Handle a generic incoming packet from a player.
Parameters
sessionId Unique identifier of the player sending the packet
packet Reference to the received Packet
Definition at line 429 of file GameManager.cpp.
References _mutex, _playerSystem, rtp::log::info(), and rtp::net::SetReadyPayload::isReady.
Referenced by processNetworkEvents().
handleUpdateSelectedWeapon()
void rtp::server::GameManager::handleUpdateSelectedWeapon (uint32_t sessionId, const net::Packet & packet) private
Handle an update to the selected weapon sent by client.
Definition at line 441 of file GameManager.cpp.
References _entitySystem, _mutex, _playerSystem, rtp::log::info(), and rtp::log::warning().
Referenced by processNetworkEvents().
processNetworkEvents()
void rtp::server::GameManager::processNetworkEvents (void) private
Process incoming network events with OpCode handling.
Note
Handles player connections, disconnections, and packet processing
Definition at line 165 of file GameManager.cpp.
References _networkManager, _networkSyncSystem, handleCreateRoom(), handleJoinRoom(), handleLeaveRoom(), handleListRooms(), handlePacket(), handlePing(), handlePlayerConnect(), handlePlayerDisconnect(), handlePlayerLoginAuth(), handlePlayerRegisterAuth(), handleRoomChatSended(), handleSetReady(), handleUpdateSelectedWeapon(), and rtp::server::None.
Referenced by gameLoop().
sendChatToSession()
void rtp::server::GameManager::sendChatToSession (uint32_t sessionId, const std::string & message) private
Definition at line 658 of file GameManager.cpp.
References _networkManager, rtp::net::RoomChatReceivedPayload::message, rtp::net::RoomChatReceived, rtp::net::RoomChatReceivedPayload::sessionId, rtp::net::TCP, and rtp::net::RoomChatReceivedPayload::username.
Referenced by handleChatCommand().
sendEntitySpawnToSessions()
void rtp::server::GameManager::sendEntitySpawnToSessions (const ecs::Entity & entity, const std::vector< uint32_t > & sessions) private
Definition at line 692 of file GameManager.cpp.
References _networkSyncSystem, _registry, rtp::net::EntitySpawn, rtp::log::error(), rtp::ecs::Entity::index(), and rtp::net::TCP.
Referenced by GameManager().
sendRoomEntitySpawnsToSession()
void rtp::server::GameManager::sendRoomEntitySpawnsToSession (uint32_t roomId, uint32_t sessionId) private
Definition at line 748 of file GameManager.cpp.
References _networkSyncSystem, _registry, rtp::net::EntitySpawn, and rtp::net::TCP.
Referenced by handleJoinRoom().
sendSystemMessageToRoom()
void rtp::server::GameManager::sendSystemMessageToRoom (uint32_t roomId, const std::string & message) private
Definition at line 671 of file GameManager.cpp.
References _networkManager, _roomSystem, rtp::net::RoomChatReceivedPayload::message, rtp::net::RoomChatReceived, rtp::net::RoomChatReceivedPayload::sessionId, rtp::net::TCP, and rtp::net::RoomChatReceivedPayload::username.
Referenced by handleChatCommand().
startGame()
void rtp::server::GameManager::startGame (Room & room)
Start a game in the specified room.
Parameters
room Reference to the Room where the game will start
Member Data Documentation
_authSystem
std::unique_ptr<AuthSystem> rtp::server::GameManager::_authSystem private
Authentication system for handling player logins.
Definition at line 204 of file GameManager.hpp.
Referenced by GameManager(), handlePlayerLoginAuth(), and handlePlayerRegisterAuth().
_boomerangSystem
std::unique_ptr<BoomerangSystem> rtp::server::GameManager::_boomerangSystem private
Boomerang system for boomerang projectiles.
Definition at line 213 of file GameManager.hpp.
Referenced by GameManager(), and gameLoop().
_bulletCleanupSystem
std::unique_ptr<BulletCleanupSystem> rtp::server::GameManager::_bulletCleanupSystem private
Bullet cleanup system.
Definition at line 216 of file GameManager.hpp.
Referenced by GameManager(), and gameLoop().
_collisionSystem
std::unique_ptr<CollisionSystem> rtp::server::GameManager::_collisionSystem private
Collision system for pickups/obstacles.
Definition at line 214 of file GameManager.hpp.
Referenced by GameManager(), gameLoop(), and handleChatCommand().
_enemyAISystem
std::unique_ptr<EnemyAISystem> rtp::server::GameManager::_enemyAISystem private
Enemy AI system for movement patterns.
Definition at line 210 of file GameManager.hpp.
Referenced by GameManager(), and gameLoop().
_enemyShootSystem
std::unique_ptr<EnemyShootSystem> rtp::server::GameManager::_enemyShootSystem private
Enemy shooting system.
Definition at line 215 of file GameManager.hpp.
Referenced by GameManager(), and gameLoop().
_entitySystem
std::unique_ptr<EntitySystem> rtp::server::GameManager::_entitySystem private
Entity system for handling entity-related operations.
Definition at line 207 of file GameManager.hpp.
Referenced by GameManager(), and handleUpdateSelectedWeapon().
_gamePaused
bool rtp::server::GameManager::_gamePaused = false private
Global game pause flag.
Definition at line 220 of file GameManager.hpp.
Referenced by gameLoop(), and handleChatCommand().
_gameSpeed
float rtp::server::GameManager::_gameSpeed = 1.0f private
Global game speed multiplier.
Definition at line 221 of file GameManager.hpp.
Referenced by gameLoop(), and handleChatCommand().
_homingSystem
std::unique_ptr<HomingSystem> rtp::server::GameManager::_homingSystem private
Homing system for tracker bullets.
Definition at line 212 of file GameManager.hpp.
Referenced by GameManager(), and gameLoop().
_levelSystem
std::unique_ptr<LevelSystem> rtp::server::GameManager::_levelSystem private
Level system for timed spawns.
Definition at line 211 of file GameManager.hpp.
Referenced by GameManager(), and gameLoop().
_movementSystem
std::unique_ptr<MovementSystem> rtp::server::GameManager::_movementSystem private
Movement system for updating entity positions.
Definition at line 203 of file GameManager.hpp.
Referenced by GameManager(), and gameLoop().
_mutex
std::mutex rtp::server::GameManager::_mutex mutable private
Mutex for thread-safe operations.
Definition at line 219 of file GameManager.hpp.
Referenced by handleCreateRoom(), handleJoinRoom(), handleLeaveRoom(), handlePacket(), handlePlayerDisconnect(), handlePlayerLoginAuth(), handlePlayerRegisterAuth(), handleRoomChatSended(), handleSetReady(), and handleUpdateSelectedWeapon().
_networkManager
ServerNetwork& rtp::server::GameManager::_networkManager private
Reference to the ServerNetwork instance.
Definition at line 198 of file GameManager.hpp.
Referenced by GameManager(), handleChatCommand(), handleCreateRoom(), handleJoinRoom(), handlePing(), handlePlayerDisconnect(), handleRoomChatSended(), processNetworkEvents(), sendChatToSession(), and sendSystemMessageToRoom().
_networkSyncSystem
std::unique_ptr<NetworkSyncSystem> rtp::server::GameManager::_networkSyncSystem private
Server network system for handling network-related ECS operations.
Definition at line 202 of file GameManager.hpp.
Referenced by GameManager(), handlePlayerDisconnect(), processNetworkEvents(), sendEntitySpawnToSessions(), and sendRoomEntitySpawnsToSession().
_playerMouvementSystem
std::unique_ptr<PlayerMouvementSystem> rtp::server::GameManager::_playerMouvementSystem private
Player movement system for handling player-specific movement logic.
Definition at line 208 of file GameManager.hpp.
Referenced by GameManager(), and gameLoop().
_playerShootSystem
std::unique_ptr<PlayerShootSystem> rtp::server::GameManager::_playerShootSystem private
Player shooting system for handling bullets.
Definition at line 209 of file GameManager.hpp.
Referenced by GameManager(), and gameLoop().
_playerSystem
std::unique_ptr<PlayerSystem> rtp::server::GameManager::_playerSystem private
Player system for handling player-related operations.
Definition at line 206 of file GameManager.hpp.
Referenced by GameManager(), handleChatCommand(), handleCreateRoom(), handleJoinRoom(), handleLeaveRoom(), handlePlayerDisconnect(), handlePlayerLoginAuth(), handlePlayerRegisterAuth(), handleRoomChatSended(), handleSetReady(), and handleUpdateSelectedWeapon().
_registry
ecs::Registry rtp::server::GameManager::_registry private
ECS Registry for managing entities and components.
Definition at line 200 of file GameManager.hpp.
Referenced by GameManager(), handlePlayerDisconnect(), sendEntitySpawnToSessions(), and sendRoomEntitySpawnsToSession().
_roomSystem
std::unique_ptr<RoomSystem> rtp::server::GameManager::_roomSystem private
Room system for handling room management.
Definition at line 205 of file GameManager.hpp.
Referenced by GameManager(), gameLoop(), handleChatCommand(), handleCreateRoom(), handleJoinRoom(), handleLeaveRoom(), handleListRooms(), handlePlayerDisconnect(), handlePlayerLoginAuth(), handlePlayerRegisterAuth(), handleRoomChatSended(), and sendSystemMessageToRoom().
_serverTick
uint32_t rtp::server::GameManager::_serverTick = 0 private
Current server tick for synchronization.
Definition at line 218 of file GameManager.hpp.
Referenced by gameLoop().
The documentation for this class was generated from the following files:
server/include/Game/GameManager.hpp
server/src/Game/GameManager.cpp