Air-Trap: rtp::ecs::Registry Class Reference
rtp::ecs::Registry Class Reference
#include <Registry.hpp>
Public Member Functions
~Registry () noexcept=default
auto spawn (void) -> std::expected< Entity, rtp::Error >
void kill (Entity entity)
template<Component T, typename Self>
auto subscribe (this Self &self) -> std::expected< std::reference_wrapper< ConstLike< Self, SparseArray< T > > >, rtp::Error >
bool isAlive (Entity entity) const noexcept
template<Component T, typename... Args>
auto add (Entity entity, Args &&...args) -> std::expected< std::reference_wrapper< T >, rtp::Error >
template<Component T, typename Self>
auto get (this const Self &self) -> std::expected< std::reference_wrapper< ConstLike< Self, SparseArray< T > > >, rtp::Error >
template<Component T>
bool has (Entity entity) const noexcept
template<Component T>
void remove (Entity entity) noexcept
void clear (void) noexcept
void purge (void) noexcept
template<Component... Ts, typename Self>
auto view (this Self &self)
template<Component... Ts, typename Self>
auto zipView (this Self &self)
std::size_t entityCount (void) const noexcept
template<Component... Ts>
std::size_t componentCount (void) const noexcept
Private Member Functions
template<Component T, typename Self>
auto getArray (this Self &self) -> ConstLikeRef< Self, SparseArray< T > >
template<Component T, Component... Ts, typename Self>
auto & getSmallestArray (this Self &self)
template<Component... Ts>
bool hasAllComponents (Entity entity) const noexcept
Private Attributes
std::unordered_map< std::type_index, std::unique_ptr< ISparseArray > > _arrays
Registered component arrays.
std::vector< std::uint32_t > _generations
Generation counters for entities.
std::deque< std::size_t > _freeIndices
Recyclable entity indices.
std::shared_mutex _mutex
Mutex for thread-safe operations.
Detailed Description
Definition at line 45 of file Registry.hpp.
Constructor & Destructor Documentation
~Registry()
rtp::ecs::Registry::~Registry () default noexcept
References kill(), and spawn().
Member Function Documentation
add()
template<Component T, typename... Args> auto rtp::ecs::Registry::add (Entity entity, Args &&... args)->std::expected< std::reference_wrapper< T >, rtp::Error >
References add().
Referenced by add(), rtp::client::graphics::UiFactory::createButton(), rtp::client::graphics::UiFactory::createDropdown(), rtp::client::graphics::UiFactory::createSlider(), rtp::client::graphics::UiFactory::createSpritePreview(), rtp::client::graphics::UiFactory::createText(), and rtp::client::graphics::UiFactory::createTextInput().
clear()
void rtp::ecs::Registry::clear (void) noexcept
Definition at line 102 of file Registry.cpp.
References _arrays, _freeIndices, _generations, and _mutex.
Referenced by remove().
componentCount()
template<Component... Ts> std::size_t rtp::ecs::Registry::componentCount (void) const nodiscard noexcept
References componentCount().
Referenced by componentCount().
entityCount()
std::size_t rtp::ecs::Registry::entityCount (void) const nodiscard noexcept
Definition at line 127 of file Registry.cpp.
References _freeIndices, _generations, and _mutex.
Referenced by zipView().
get()
template<Component T, typename Self> auto rtp::ecs::Registry::get (this const Self & self) ->std::expected< std::reference_wrapper< ConstLike< Self, SparseArray< T > > >, rtp::Error > nodiscard
References get().
Referenced by get().
getArray()
template<Component T, typename Self> auto rtp::ecs::Registry::getArray (this Self & self) ->ConstLikeRef< Self, SparseArray< T > > nodiscard private
References getArray().
Referenced by getArray().
getSmallestArray()
template<Component T, Component... Ts, typename Self> auto & rtp::ecs::Registry::getSmallestArray (this Self & self) nodiscard private
References getSmallestArray().
Referenced by getSmallestArray().
has()
template<Component T> bool rtp::ecs::Registry::has (Entity entity) const nodiscard noexcept
References has().
Referenced by has().
hasAllComponents()
template<Component... Ts> bool rtp::ecs::Registry::hasAllComponents (Entity entity) const nodiscard private noexcept
References hasAllComponents().
Referenced by hasAllComponents().
isAlive()
bool rtp::ecs::Registry::isAlive (Entity entity) const nodiscard noexcept
Definition at line 90 of file Registry.cpp.
References _generations, and _mutex.
Referenced by subscribe().
kill()
void rtp::ecs::Registry::kill (Entity entity)
Definition at line 73 of file Registry.cpp.
References _arrays, _freeIndices, _generations, _mutex, rtp::ecs::Entity::generation(), and rtp::ecs::Entity::index().
Referenced by ~Registry().
purge()
void rtp::ecs::Registry::purge (void) noexcept
Definition at line 113 of file Registry.cpp.
References _arrays, _freeIndices, _generations, and _mutex.
Referenced by remove().
remove()
template<Component T> void rtp::ecs::Registry::remove (Entity entity) noexcept
References clear(), purge(), and remove().
Referenced by remove().
spawn()
auto rtp::ecs::Registry::spawn (void) ->std::expected< Entity, rtp::Error > nodiscard
Definition at line 51 of file Registry.cpp.
References _freeIndices, _generations, _mutex, rtp::Error::failure(), rtp::ecs::Entity::MAX_INDEX, and rtp::RegistryFull.
Referenced by ~Registry(), rtp::client::graphics::UiFactory::createButton(), rtp::client::graphics::UiFactory::createDropdown(), rtp::client::graphics::UiFactory::createSlider(), rtp::client::graphics::UiFactory::createSpritePreview(), rtp::client::graphics::UiFactory::createText(), and rtp::client::graphics::UiFactory::createTextInput().
subscribe()
template<Component T, typename Self> auto rtp::ecs::Registry::subscribe (this Self & self) ->std::expected< std::reference_wrapper< ConstLike< Self, SparseArray< T > > >, rtp::Error >
References isAlive(), and subscribe().
Referenced by subscribe().
view()
template<Component... Ts, typename Self> auto rtp::ecs::Registry::view (this Self & self) nodiscard
References view().
Referenced by view().
zipView()
template<Component... Ts, typename Self> auto rtp::ecs::Registry::zipView (this Self & self) nodiscard
References entityCount(), and zipView().
Referenced by zipView().
Member Data Documentation
_arrays
std::unordered_map<std::type_index, std::unique_ptr<ISparseArray> > rtp::ecs::Registry::_arrays private
Registered component arrays.
Definition at line 103 of file Registry.hpp.
Referenced by clear(), kill(), and purge().
_freeIndices
std::deque<std::size_t> rtp::ecs::Registry::_freeIndices private
Recyclable entity indices.
Definition at line 105 of file Registry.hpp.
Referenced by clear(), entityCount(), kill(), purge(), and spawn().
_generations
std::vector<std::uint32_t> rtp::ecs::Registry::_generations private
Generation counters for entities.
Definition at line 104 of file Registry.hpp.
Referenced by clear(), entityCount(), isAlive(), kill(), purge(), and spawn().
_mutex
std::shared_mutex rtp::ecs::Registry::_mutex mutable private
Mutex for thread-safe operations.
Definition at line 106 of file Registry.hpp.
Referenced by clear(), entityCount(), isAlive(), kill(), purge(), and spawn().
The documentation for this class was generated from the following files:
common/include/RType/ECS/Registry.hpp
common/src/ECS/Registry.cpp