Air-Trap: rtp::client::graphics::UiFactory Class Reference
rtp::client::graphics::UiFactory Class Reference
Factory class for creating UI components in the ECS registry.
#include <UiFactory.hpp>
Public Member Functions
UiFactory ()=default
~UiFactory ()=default
Static Public Member Functions
static ecs::Entity createButton (ecs::Registry &registry, const position &position, const size &size, const std::string &label, std::function< void()> onClick=nullptr)
Create a button UI component.
static ecs::Entity createText (ecs::Registry &registry, const position &position, const std::string &content, const std::string &fontPath, unsigned int fontSize, const std::uint8_t zIndex=0, const color &textColor={255, 255, 255})
static ecs::Entity createSlider (ecs::Registry &registry, const position &position, const size &size, float minValue, float maxValue, float initialValue, std::function< void(float)> onChange=nullptr)
static ecs::Entity createDropdown (ecs::Registry &registry, const position &position, const size &size, const std::vector< std::string > &options, const int selectedIndex, std::function< void(int index)> onSelect=nullptr)
static ecs::Entity createTextInput (ecs::Registry &registry, const position &position, const size &size, const std::string &fontPath, unsigned int fontSize, const int maxLength=64, const std::string &placeholder="", std::function< void(const std::string &)> onSubmit=nullptr, std::function< void(const std::string &)> onChange=nullptr)
static ecs::Entity createSpritePreview (ecs::Registry &registry, const position &position, const std::string &texturePath, int rectLeft, int rectTop, int rectWidth, int rectHeight, float scale=2.0f, int zIndex=0)
Create a sprite preview UI component.
Detailed Description
Factory class for creating UI components in the ECS registry.
This class provides static methods to create various UI elements
such as buttons, text fields, sliders, etc., and add them to the
provided ECS registry.
Definition at line 72 of file UiFactory.hpp.
Constructor & Destructor Documentation
UiFactory()
rtp::client::graphics::UiFactory::UiFactory () default
~UiFactory()
rtp::client::graphics::UiFactory::~UiFactory () default
Member Function Documentation
createButton()
ecs::Entity rtp::client::graphics::UiFactory::createButton (ecs::Registry & registry, const position & position, const size & size, const std::string & label, std::function< void()> onClick = nullptr) static
Create a button UI component.
Parameters
registry Reference to the ECS registry.
x X position of the button.
y Y position of the button.
width Width of the button.
height Height of the button.
label Text label of the button.
onClick Callback function to be called when the button is clicked.
Returns
The created entity representing the button.
Definition at line 17 of file UiFactory.cpp.
References rtp::ecs::Registry::add(), rtp::log::error(), rtp::client::graphics::size::height, rtp::ecs::components::ui::Button::onClick, rtp::ecs::components::ui::Button::position, rtp::ecs::components::ui::Button::size, rtp::ecs::Registry::spawn(), rtp::ecs::components::ui::Button::text, rtp::client::graphics::size::width, rtp::client::graphics::position::x, and rtp::client::graphics::position::y.
createDropdown()
ecs::Entity rtp::client::graphics::UiFactory::createDropdown (ecs::Registry & registry, const position & position, const size & size, const std::vector< std::string > & options, const int selectedIndex, std::function< void(int index)> onSelect = nullptr) static
            @brief Create a dropdown UI component.
            * @param registry Reference to the ECS registry.
Parameters
x X position of the dropdown.
y Y position of the dropdown.
width Width of the dropdown.
height Height of the dropdown.
options List of options for the dropdown.
selectedIndex Index of the initially selected option.
Parameters
onSelect Callback function to be called when an option is selected.
Returns
The created entity representing the dropdown.
Definition at line 106 of file UiFactory.cpp.
References rtp::ecs::Registry::add(), rtp::log::error(), rtp::client::graphics::size::height, rtp::ecs::components::ui::Dropdown::onSelect, rtp::ecs::components::ui::Dropdown::options, rtp::ecs::components::ui::Dropdown::position, rtp::ecs::components::ui::Dropdown::selectedIndex, rtp::ecs::components::ui::Dropdown::size, rtp::ecs::Registry::spawn(), rtp::log::warning(), rtp::client::graphics::size::width, rtp::client::graphics::position::x, and rtp::client::graphics::position::y.
createSlider()
ecs::Entity rtp::client::graphics::UiFactory::createSlider (ecs::Registry & registry, const position & position, const size & size, float minValue, float maxValue, float initialValue, std::function< void(float)> onChange = nullptr) static
            @brief Create a slider UI component.
            * @param registry Reference to the ECS registry.
Parameters
x X position of the slider.
y Y position of the slider.
width Width of the slider.
height Height of the slider.
minValue Minimum value of the slider.
maxValue Maximum value of the slider.
initialValue Initial value of the slider.
onChange Callback function to be called when the slider value changes.
Returns
The created entity representing the slider.
Definition at line 75 of file UiFactory.cpp.
References rtp::ecs::Registry::add(), rtp::ecs::components::ui::Slider::currentValue, rtp::log::error(), rtp::client::graphics::size::height, rtp::ecs::components::ui::Slider::maxValue, rtp::ecs::components::ui::Slider::minValue, rtp::ecs::components::ui::Slider::onChange, rtp::ecs::components::ui::Slider::position, rtp::ecs::components::ui::Slider::size, rtp::ecs::Registry::spawn(), rtp::client::graphics::size::width, rtp::client::graphics::position::x, and rtp::client::graphics::position::y.
createSpritePreview()
ecs::Entity rtp::client::graphics::UiFactory::createSpritePreview (ecs::Registry & registry, const position & position, const std::string & texturePath, int rectLeft, int rectTop, int rectWidth, int rectHeight, float scale = 2.0f, int zIndex = 0) static
Create a sprite preview UI component.
Parameters
registry Reference to the ECS registry.
position Position of the sprite preview.
texturePath Path to the texture file.
rectLeft Left coordinate in the texture.
rectTop Top coordinate in the texture.
rectWidth Width of the sprite in the texture.
rectHeight Height of the sprite in the texture.
scale Scale factor for display.
zIndex Z-index for rendering order.
Returns
The created entity representing the sprite preview.
Definition at line 177 of file UiFactory.cpp.
References rtp::ecs::Registry::add(), rtp::log::error(), rtp::ecs::components::ui::SpritePreview::rectHeight, rtp::ecs::components::ui::SpritePreview::rectLeft, rtp::ecs::components::ui::SpritePreview::rectTop, rtp::ecs::components::ui::SpritePreview::rectWidth, rtp::ecs::components::ui::SpritePreview::scale, rtp::ecs::Registry::spawn(), rtp::ecs::components::ui::SpritePreview::texturePath, rtp::client::graphics::position::x, rtp::ecs::components::ui::SpritePreview::x, rtp::client::graphics::position::y, rtp::ecs::components::ui::SpritePreview::y, and rtp::ecs::components::ui::SpritePreview::zIndex.
createText()
ecs::Entity rtp::client::graphics::UiFactory::createText (ecs::Registry & registry, const position & position, const std::string & content, const std::string & fontPath, unsigned int fontSize, const std::uint8_t zIndex = 0, const color & textColor = {255, 255, 255}) static
            @brief Create a text UI component.
            * @param registry Reference to the ECS registry.
Parameters
x X position of the text.
y Y position of the text.
content Text content.
fontPath Path to the font file.
fontSize Size of the font.
Parameters
zIndex Z-index for rendering order.
textColor Color of the text.
Returns
The created entity representing the text.
Definition at line 43 of file UiFactory.cpp.
References rtp::ecs::Registry::add(), rtp::client::graphics::color::b, rtp::ecs::components::ui::Text::blue, rtp::ecs::components::ui::Text::content, rtp::log::error(), rtp::ecs::components::ui::Text::fontPath, rtp::ecs::components::ui::Text::fontSize, rtp::client::graphics::color::g, rtp::ecs::components::ui::Text::green, rtp::ecs::components::ui::Text::position, rtp::client::graphics::color::r, rtp::ecs::components::ui::Text::red, rtp::ecs::Registry::spawn(), rtp::client::graphics::position::x, rtp::client::graphics::position::y, and rtp::ecs::components::ui::Text::zIndex.
createTextInput()
ecs::Entity rtp::client::graphics::UiFactory::createTextInput (ecs::Registry & registry, const position & position, const size & size, const std::string & fontPath, unsigned int fontSize, const int maxLength = 64, const std::string & placeholder = "", std::function< void(const std::string &)> onSubmit = nullptr, std::function< void(const std::string &)> onChange = nullptr) static
            @brief Create a text input UI component.
            * @param registry Reference to the ECS registry.
Parameters
x X position of the text input.
y Y position of the text input.
width Width of the text input.
height Height of the text input.
fontPath Path to the font file.
fontSize Size of the font.
maxLength Maximum length of the input text.
placeholder Placeholder text when input is empty.
onChange Callback function to be called when the text changes.
Returns
The created entity representing the text input.
Definition at line 142 of file UiFactory.cpp.
References rtp::ecs::Registry::add(), rtp::log::error(), rtp::ecs::components::ui::TextInput::fontPath, rtp::ecs::components::ui::TextInput::fontSize, rtp::client::graphics::size::height, rtp::ecs::components::ui::TextInput::maxLength, rtp::ecs::components::ui::TextInput::onChange, rtp::ecs::components::ui::TextInput::onSubmit, rtp::ecs::components::ui::TextInput::placeholder, rtp::ecs::components::ui::TextInput::position, rtp::ecs::components::ui::TextInput::size, rtp::ecs::Registry::spawn(), rtp::client::graphics::size::width, rtp::client::graphics::position::x, and rtp::client::graphics::position::y.
The documentation for this class was generated from the following files:
client/include/UI/UiFactory.hpp
client/src/UI/UiFactory.cpp