Air-Trap: rtp::client::scenes::ModMenuScene Class Reference
rtp::client::scenes::ModMenuScene Class Reference
Scene for customizing game sprites.
#include <ModMenuScene.hpp>
Public Types
using ChangeStateFn = std::function<void(GameState)>
Type alias for a function that changes the game state.
Public Member Functions
ModMenuScene (ecs::Registry &UiRegistry, Settings &settings, TranslationManager &translationManager, graphics::UiFactory &uiFactory, std::function< void(GameState)> changeState)
Constructor for ModMenuScene.
void onEnter (void) override
Called when the scene is entered.
void onExit (void) override
Called when the scene is exited.
void handleEvent (const sf::Event &event) override
Handle an incoming event.
void update (float dt) override
Update the scene state.
Public Member Functions inherited from rtp::client::interfaces::IScene
virtual ~IScene (void)=default
Private Member Functions
void initializeModDirectory ()
Initialize the custom sprites directory.
void loadEntityCategories ()
Load all entity categories and their sprites.
void showCategoryList ()
Show the main category selection screen.
void showEntityCodex (size_t categoryIndex)
Show the entity codex for a specific category.
sf::Texture * loadTexture (const std::string &texturePath)
Load a texture if not already loaded.
std::string openFileDialog ()
Open file dialog to select a custom sprite.
void saveSpriteMappings ()
Save custom sprite mappings to config file.
void loadSpriteMappings ()
Load custom sprite mappings from config file.
void applyCustomSprite (const EntitySpriteInfo &entity, const std::string &categoryName)
Apply a custom sprite to an entity.
sf::Image resizeImage (const sf::Image &sourceImage, unsigned int targetWidth, unsigned int targetHeight)
Resize an image to match target dimensions.
std::string getEntityKey (const EntitySpriteInfo &entity) const
Get the unique key for an entity.
Private Attributes
ecs::Registry & _uiRegistry
Reference to the ECS registry.
Settings & _settings
Reference to the application settings.
TranslationManager & _translationManager
Reference to the translation manager.
graphics::UiFactory & _uiFactory
UI Factory for creating UI components.
ChangeStateFn _changeState
Function to change the game state.
std::filesystem::path _customSpritesPath
Path to custom sprites directory.
std::filesystem::path _spriteMappingPath
Path to sprite mapping config file.
std::vector< EntityCategory > _categories
Available entity categories with their sprites.
size_t _selectedCategoryIndex
Currently selected category index.
bool _showingCategoryList
True if showing category list, false if showing entity codex.
std::map< std::string, sf::Texture > _loadedTextures
Cache of loaded textures.
std::unordered_map< std::string, std::string > _customSpriteMappings
Detailed Description
Scene for customizing game sprites.
This scene allows players to replace game sprites with custom ones. Players can modify sprites for entities, enemies, projectiles, etc.
Definition at line 55 of file ModMenuScene.hpp.
Member Typedef Documentation
ChangeStateFn
using rtp::client::scenes::ModMenuScene::ChangeStateFn = std::function<void(GameState)>
Type alias for a function that changes the game state.
Definition at line 75 of file ModMenuScene.hpp.
Constructor & Destructor Documentation
ModMenuScene()
rtp::client::scenes::ModMenuScene::ModMenuScene (ecs::Registry & UiRegistry, Settings & settings, TranslationManager & translationManager, graphics::UiFactory & uiFactory, std::function< void(GameState)> changeState)
Constructor for ModMenuScene.
Parameters
registry Reference to the ECS registry
settings Reference to the application settings
translationManager Reference to the translation manager
uiFactory Reference to the UI factory
changeState Function to change the game state
Definition at line 20 of file ModMenuScene.cpp.
References _changeState, _customSpritesPath, _selectedCategoryIndex, _settings, _showingCategoryList, _spriteMappingPath, _translationManager, _uiFactory, _uiRegistry, initializeModDirectory(), loadEntityCategories(), and loadSpriteMappings().
Member Function Documentation
applyCustomSprite()
void rtp::client::scenes::ModMenuScene::applyCustomSprite (const EntitySpriteInfo & entity, const std::string & categoryName) private
Apply a custom sprite to an entity.
Parameters
entity Entity information
categoryName Category name for organizing sprites
Definition at line 474 of file ModMenuScene.cpp.
References _customSpriteMappings, _customSpritesPath, _loadedTextures, _selectedCategoryIndex, _uiRegistry, applyCustomSprite(), rtp::client::SpriteCustomizer::clearTextureCaches(), rtp::log::error(), getEntityKey(), rtp::client::SpriteCustomizer::getInstance(), rtp::log::info(), openFileDialog(), rtp::client::scenes::EntitySpriteInfo::rectHeight, rtp::client::scenes::EntitySpriteInfo::rectWidth, rtp::client::SpriteCustomizer::reloadMappings(), resizeImage(), saveSpriteMappings(), and showEntityCodex().
Referenced by applyCustomSprite().
getEntityKey()
std::string rtp::client::scenes::ModMenuScene::getEntityKey (const EntitySpriteInfo & entity) const private
Get the unique key for an entity.
Parameters
entity Entity information
Returns
Unique key string
Definition at line 372 of file ModMenuScene.cpp.
References getEntityKey(), and rtp::client::scenes::EntitySpriteInfo::name.
Referenced by applyCustomSprite(), getEntityKey(), and showEntityCodex().
handleEvent()
void rtp::client::scenes::ModMenuScene::handleEvent (const sf::Event & event) override virtual
Handle an incoming event.
Parameters
event The event to handle.
Implements rtp::client::interfaces::IScene.
Definition at line 55 of file ModMenuScene.cpp.
References _changeState, _showingCategoryList, _uiRegistry, rtp::client::SpriteCustomizer::getInstance(), rtp::client::Menu, rtp::client::SpriteCustomizer::reloadMappings(), and showCategoryList().
initializeModDirectory()
void rtp::client::scenes::ModMenuScene::initializeModDirectory () private
Initialize the custom sprites directory.
Definition at line 81 of file ModMenuScene.cpp.
References _customSpritesPath, rtp::log::error(), and rtp::log::info().
Referenced by ModMenuScene().
loadEntityCategories()
void rtp::client::scenes::ModMenuScene::loadEntityCategories () private
Load all entity categories and their sprites.
Definition at line 122 of file ModMenuScene.cpp.
References _categories, rtp::client::scenes::EntityCategory::entities, and rtp::client::scenes::EntityCategory::name.
Referenced by ModMenuScene().
loadSpriteMappings()
void rtp::client::scenes::ModMenuScene::loadSpriteMappings () private
Load custom sprite mappings from config file.
Definition at line 393 of file ModMenuScene.cpp.
References _customSpriteMappings, _spriteMappingPath, rtp::log::error(), rtp::log::info(), loadSpriteMappings(), and rtp::config::loadSpriteMappings().
Referenced by ModMenuScene(), loadSpriteMappings(), and onEnter().
loadTexture()
sf::Texture * rtp::client::scenes::ModMenuScene::loadTexture (const std::string & texturePath) private
Load a texture if not already loaded.
Parameters
texturePath Path to the texture file
Returns
Pointer to the texture, or nullptr if failed
Definition at line 355 of file ModMenuScene.cpp.
References _loadedTextures, rtp::log::error(), and loadTexture().
Referenced by loadTexture().
onEnter()
void rtp::client::scenes::ModMenuScene::onEnter (void) override virtual
Called when the scene is entered.
Implements rtp::client::interfaces::IScene.
Definition at line 40 of file ModMenuScene.cpp.
References _loadedTextures, _showingCategoryList, rtp::log::info(), loadSpriteMappings(), and showCategoryList().
onExit()
void rtp::client::scenes::ModMenuScene::onExit (void) override virtual
Called when the scene is exited.
Implements rtp::client::interfaces::IScene.
Definition at line 49 of file ModMenuScene.cpp.
References _loadedTextures, and rtp::log::info().
openFileDialog()
std::string rtp::client::scenes::ModMenuScene::openFileDialog () private
Open file dialog to select a custom sprite.
Returns
Selected file path, or empty string if cancelled
Definition at line 408 of file ModMenuScene.cpp.
References rtp::log::error(), and openFileDialog().
Referenced by applyCustomSprite(), and openFileDialog().
resizeImage()
sf::Image rtp::client::scenes::ModMenuScene::resizeImage (const sf::Image & sourceImage, unsigned int targetWidth, unsigned int targetHeight) private
Resize an image to match target dimensions.
Parameters
sourceImage Source image to resize
targetWidth Target width
targetHeight Target height
Returns
Resized image
Definition at line 457 of file ModMenuScene.cpp.
References resizeImage().
Referenced by applyCustomSprite(), and resizeImage().
saveSpriteMappings()
void rtp::client::scenes::ModMenuScene::saveSpriteMappings () private
Save custom sprite mappings to config file.
Definition at line 380 of file ModMenuScene.cpp.
References _customSpriteMappings, _spriteMappingPath, rtp::log::error(), rtp::log::info(), saveSpriteMappings(), and rtp::config::saveSpriteMappings().
Referenced by applyCustomSprite(), and saveSpriteMappings().
showCategoryList()
void rtp::client::scenes::ModMenuScene::showCategoryList () private
Show the main category selection screen.
Definition at line 169 of file ModMenuScene.cpp.
References _categories, _changeState, _selectedCategoryIndex, _showingCategoryList, _translationManager, _uiFactory, _uiRegistry, rtp::client::SpriteCustomizer::getInstance(), rtp::client::Menu, rtp::client::SpriteCustomizer::reloadMappings(), and showEntityCodex().
Referenced by handleEvent(), and onEnter().
showEntityCodex()
void rtp::client::scenes::ModMenuScene::showEntityCodex (size_t categoryIndex) private
Show the entity codex for a specific category.
Parameters
categoryIndex Index of the category to display
Definition at line 229 of file ModMenuScene.cpp.
References _categories, _customSpriteMappings, _uiFactory, _uiRegistry, rtp::log::error(), and getEntityKey().
Referenced by applyCustomSprite(), and showCategoryList().
update()
void rtp::client::scenes::ModMenuScene::update (float dt) override virtual
Update the scene state.
Parameters
dt Time delta since the last update.
Implements rtp::client::interfaces::IScene.
Definition at line 72 of file ModMenuScene.cpp.
Member Data Documentation
_categories
std::vector<EntityCategory> rtp::client::scenes::ModMenuScene::_categories private
Available entity categories with their sprites.
Definition at line 108 of file ModMenuScene.hpp.
Referenced by loadEntityCategories(), showCategoryList(), and showEntityCodex().
_changeState
ChangeStateFn rtp::client::scenes::ModMenuScene::_changeState private
Function to change the game state.
Definition at line 104 of file ModMenuScene.hpp.
Referenced by ModMenuScene(), handleEvent(), and showCategoryList().
_customSpriteMappings
std::unordered_map<std::string, std::string> rtp::client::scenes::ModMenuScene::_customSpriteMappings private
Definition at line 116 of file ModMenuScene.hpp.
Referenced by applyCustomSprite(), loadSpriteMappings(), saveSpriteMappings(), and showEntityCodex().
_customSpritesPath
std::filesystem::path rtp::client::scenes::ModMenuScene::_customSpritesPath private
Path to custom sprites directory.
Definition at line 106 of file ModMenuScene.hpp.
Referenced by ModMenuScene(), applyCustomSprite(), and initializeModDirectory().
_loadedTextures
std::map<std::string, sf::Texture> rtp::client::scenes::ModMenuScene::_loadedTextures private
Cache of loaded textures.
Definition at line 113 of file ModMenuScene.hpp.
Referenced by applyCustomSprite(), loadTexture(), onEnter(), and onExit().
_selectedCategoryIndex
size_t rtp::client::scenes::ModMenuScene::_selectedCategoryIndex private
Currently selected category index.
Definition at line 109 of file ModMenuScene.hpp.
Referenced by ModMenuScene(), applyCustomSprite(), and showCategoryList().
_settings
Settings& rtp::client::scenes::ModMenuScene::_settings private
Reference to the application settings.
Definition at line 101 of file ModMenuScene.hpp.
Referenced by ModMenuScene().
_showingCategoryList
bool rtp::client::scenes::ModMenuScene::_showingCategoryList private
True if showing category list, false if showing entity codex.
Definition at line 110 of file ModMenuScene.hpp.
Referenced by ModMenuScene(), handleEvent(), onEnter(), and showCategoryList().
_spriteMappingPath
std::filesystem::path rtp::client::scenes::ModMenuScene::_spriteMappingPath private
Path to sprite mapping config file.
Definition at line 107 of file ModMenuScene.hpp.
Referenced by ModMenuScene(), loadSpriteMappings(), and saveSpriteMappings().
_translationManager
TranslationManager& rtp::client::scenes::ModMenuScene::_translationManager private
Reference to the translation manager.
Definition at line 102 of file ModMenuScene.hpp.
Referenced by ModMenuScene(), and showCategoryList().
_uiFactory
graphics::UiFactory& rtp::client::scenes::ModMenuScene::_uiFactory private
UI Factory for creating UI components.
Definition at line 103 of file ModMenuScene.hpp.
Referenced by ModMenuScene(), showCategoryList(), and showEntityCodex().
_uiRegistry
ecs::Registry& rtp::client::scenes::ModMenuScene::_uiRegistry private
Reference to the ECS registry.
Definition at line 100 of file ModMenuScene.hpp.
Referenced by ModMenuScene(), applyCustomSprite(), handleEvent(), showCategoryList(), and showEntityCodex().
The documentation for this class was generated from the following files:
client/include/Scenes/ModMenuScene.hpp
client/src/Scenes/ModMenuScene.cpp