Air-Trap: rtp::ecs::ZipView< Containers >::Iterator Class Reference
rtp::ecs::ZipView< Containers >::Iterator Class Reference
The actual iterator performing the intersection logic.
#include <ZipView.hpp>
Public Types
using iterator_category = std::forward_iterator_tag
using value_type = std::tuple<typename std::remove_reference_t<Containers>::value_type&...>
using difference_type = std::ptrdiff_t
using pointer = void
using reference = value_type
Public Member Functions
Iterator (tuple_arrays_t &arrays, std::span< const Entity > entities, size_t index)
Iterator & operator++ ()
Iterator operator++ (int)
bool operator== (const Iterator &other) const
bool operator!= (const Iterator &other) const
reference operator* ()
Private Member Functions
void skipInvalid ()
Skip to the next valid entity that has all components.
Private Attributes
tuple_arrays_t & _arrays
Tuple of references to SparseArrays.
std::span< const Entity > _entities
Entities of the leader SparseArray.
size_t _index
Current index in the entity list.
Detailed Description
template<class... Containers>
class rtp::ecs::ZipView< Containers >::Iterator
The actual iterator performing the intersection logic.
Definition at line 37 of file ZipView.hpp.
Member Typedef Documentation
difference_type
template<class... Containers> using rtp::ecs::ZipView< Containers >::Iterator::difference_type = std::ptrdiff_t
Definition at line 41 of file ZipView.hpp.
iterator_category
template<class... Containers> using rtp::ecs::ZipView< Containers >::Iterator::iterator_category = std::forward_iterator_tag
Definition at line 39 of file ZipView.hpp.
pointer
template<class... Containers> using rtp::ecs::ZipView< Containers >::Iterator::pointer = void
Definition at line 42 of file ZipView.hpp.
reference
template<class... Containers> using rtp::ecs::ZipView< Containers >::Iterator::reference = value_type
Definition at line 43 of file ZipView.hpp.
value_type
template<class... Containers> using rtp::ecs::ZipView< Containers >::Iterator::value_type = std::tuple<typename std::remove_reference_t<Containers>::value_type&...>
Definition at line 40 of file ZipView.hpp.
Constructor & Destructor Documentation
Iterator()
template<class... Containers> rtp::ecs::ZipView< Containers >::Iterator::Iterator (tuple_arrays_t & arrays, std::span< const Entity > entities, size_t index) inline
Definition at line 45 of file ZipView.hpp.
References _arrays, _entities, _index, and skipInvalid().
Referenced by operator!=(), operator++(), operator++(), and operator==().
Member Function Documentation
operator!=()
template<class... Containers> bool rtp::ecs::ZipView< Containers >::Iterator::operator!= (const Iterator & other) const inline
Definition at line 69 of file ZipView.hpp.
References Iterator(), and _index.
operator*()
template<class... Containers> reference rtp::ecs::ZipView< Containers >::Iterator::operator* () inline nodiscard
Definition at line 74 of file ZipView.hpp.
References _arrays, _entities, and _index.
operator++() [1/2]
template<class... Containers> Iterator & rtp::ecs::ZipView< Containers >::Iterator::operator++ () inline
Definition at line 53 of file ZipView.hpp.
References Iterator(), _index, and skipInvalid().
operator++() [2/2]
template<class... Containers> Iterator rtp::ecs::ZipView< Containers >::Iterator::operator++ (int) inline
Definition at line 59 of file ZipView.hpp.
References Iterator().
operator==()
template<class... Containers> bool rtp::ecs::ZipView< Containers >::Iterator::operator== (const Iterator & other) const inline
Definition at line 65 of file ZipView.hpp.
References Iterator(), and _index.
skipInvalid()
template<class... Containers> void rtp::ecs::ZipView< Containers >::Iterator::skipInvalid () inline private
Skip to the next valid entity that has all components.
Definition at line 89 of file ZipView.hpp.
References _arrays, _entities, and _index.
Referenced by Iterator(), and operator++().
Member Data Documentation
_arrays
template<class... Containers> tuple_arrays_t& rtp::ecs::ZipView< Containers >::Iterator::_arrays private
Tuple of references to SparseArrays.
Definition at line 82 of file ZipView.hpp.
Referenced by Iterator(), operator*(), and skipInvalid().
_entities
template<class... Containers> std::span<const Entity> rtp::ecs::ZipView< Containers >::Iterator::_entities private
Entities of the leader SparseArray.
Definition at line 83 of file ZipView.hpp.
Referenced by Iterator(), operator*(), and skipInvalid().
_index
template<class... Containers> size_t rtp::ecs::ZipView< Containers >::Iterator::_index private
Current index in the entity list.
Definition at line 84 of file ZipView.hpp.
Referenced by Iterator(), operator!=(), operator*(), operator++(), operator==(), and skipInvalid().
The documentation for this class was generated from the following file:
common/include/RType/ECS/ZipView.hpp