Air-Trap: rtp::server::EntitySystem Class Reference
rtp::server::EntitySystem Class Reference
Base class for systems that operate on entities in the ECS.
#include <EntitySystem.hpp>
Public Member Functions
EntitySystem (ecs::Registry &registry, ServerNetwork &network, NetworkSyncSystem &networkSync)
Constructor for EntitySystem.
void update (float dt) override
Update movement system logic for one frame.
ecs::Entity createPlayerEntity (PlayerPtr player)
Create a new player entity in the ECS.
ecs::Entity createPlayerEntity (PlayerPtr player, const Vec2f &spawnPos)
ecs::Entity createEnemyEntity (uint32_t roomId, const Vec2f &pos, ecs::components::Patterns pattern, float speed, float amplitude, float frequency, net::EntityType type=net::EntityType::Scout)
Create a new enemy entity in the ECS.
ecs::Entity creaetEnemyEntity (uint32_t roomId, const Vec2f &pos, ecs::components::Patterns pattern, float speed, float amplitude, float frequency)
Create a new enemy entity in the ECS with default type Scout.
ecs::Entity createPowerupEntity (uint32_t roomId, const Vec2f &pos, ecs::components::PowerupType type, float value, float duration)
Create a new powerup entity in the ECS.
ecs::Entity createObstacleEntity (uint32_t roomId, const Vec2f &pos, const Vec2f &size, int health, net::EntityType type=net::EntityType::Obstacle)
Create a new obstacle entity in the ECS.
void applyWeaponToEntity (ecs::Entity entity, ecs::components::WeaponKind weaponKind)
Apply a weapon configuration to an existing entity (player).
Public Member Functions inherited from rtp::ecs::ISystem
virtual ~ISystem () noexcept=default
Protected Attributes
ecs::Registry & _registry
Reference to the entity registry.
ServerNetwork & _network
Reference to the server network manager.
NetworkSyncSystem & _networkSync
Reference to the network sync system.
Detailed Description
Base class for systems that operate on entities in the ECS.
Definition at line 44 of file EntitySystem.hpp.
Constructor & Destructor Documentation
EntitySystem()
rtp::server::EntitySystem::EntitySystem (ecs::Registry & registry, ServerNetwork & network, NetworkSyncSystem & networkSync)
Constructor for EntitySystem.
Parameters
registry Reference to the entity registry
Definition at line 18 of file EntitySystem.cpp.
References _network, _networkSync, and _registry.
Member Function Documentation
applyWeaponToEntity()
void rtp::server::EntitySystem::applyWeaponToEntity (ecs::Entity entity, ecs::components::WeaponKind weaponKind)
Apply a weapon configuration to an existing entity (player).
Parameters
entity Target entity
weaponKind Weapon kind to apply
Definition at line 125 of file EntitySystem.cpp.
References _registry, rtp::ecs::components::SimpleWeapon::ammo, rtp::ecs::components::Beam, rtp::ecs::components::SimpleWeapon::beamCooldown, rtp::config::getWeaponDef(), rtp::config::hasWeaponConfigs(), rtp::ecs::Entity::index(), rtp::log::info(), rtp::ecs::components::SimpleWeapon::kind, rtp::ecs::components::SimpleWeapon::maxAmmo, and rtp::log::warning().
creaetEnemyEntity()
ecs::Entity rtp::server::EntitySystem::creaetEnemyEntity (uint32_t roomId, const Vec2f & pos, ecs::components::Patterns pattern, float speed, float amplitude, float frequency)
Create a new enemy entity in the ECS with default type Scout.
Parameters
roomId ID of the room the enemy belongs to
pos Position to spawn the enemy at
pattern Movement pattern for the enemy
speed Movement speed of the enemy
amplitude Amplitude for movement patterns that require it
frequency Frequency for movement patterns that require it
Returns
The ID of the created enemy entity
Definition at line 268 of file EntitySystem.cpp.
References createEnemyEntity(), and rtp::net::Scout.
createEnemyEntity()
ecs::Entity rtp::server::EntitySystem::createEnemyEntity (uint32_t roomId, const Vec2f & pos, ecs::components::Patterns pattern, float speed, float amplitude, float frequency, net::EntityType type = net::EntityType::Scout)
Create a new enemy entity in the ECS.
Returns
The ID of the created enemy entity
Definition at line 167 of file EntitySystem.cpp.
References _registry, rtp::net::Boss, rtp::net::Boss2, rtp::net::BossShield, rtp::ecs::components::Classic, rtp::ecs::components::SimpleWeapon::damage, rtp::log::error(), rtp::ecs::components::SimpleWeapon::fireRate, rtp::ecs::Entity::index(), rtp::ecs::components::SimpleWeapon::isBoomerang, rtp::ecs::components::SimpleWeapon::kind, rtp::ecs::components::SimpleWeapon::lastShotTime, rtp::net::Tank, rtp::Vec2< T >::x, and rtp::Vec2< T >::y.
Referenced by creaetEnemyEntity().
createObstacleEntity()
ecs::Entity rtp::server::EntitySystem::createObstacleEntity (uint32_t roomId, const Vec2f & pos, const Vec2f & size, int health, net::EntityType type = net::EntityType::Obstacle)
Create a new obstacle entity in the ECS.
Parameters
roomId ID of the room the obstacle belongs to
pos Position to spawn the obstacle at
size Size of the obstacle
health Health points of the obstacle
type Type of the obstacle entity
Returns
The ID of the created obstacle entity
Definition at line 323 of file EntitySystem.cpp.
References _registry, rtp::log::error(), rtp::ecs::Entity::index(), rtp::Vec2< T >::x, and rtp::Vec2< T >::y.
createPlayerEntity() [1/2]
ecs::Entity rtp::server::EntitySystem::createPlayerEntity (PlayerPtr player)
Create a new player entity in the ECS.
Returns
The ID of the created player entity
Definition at line 32 of file EntitySystem.cpp.
References createPlayerEntity().
Referenced by createPlayerEntity().
createPlayerEntity() [2/2]
ecs::Entity rtp::server::EntitySystem::createPlayerEntity (PlayerPtr player, const Vec2f & spawnPos)
Definition at line 38 of file EntitySystem.cpp.
References _registry, rtp::ecs::components::Beam, rtp::log::error(), rtp::config::getWeaponDef(), rtp::config::hasWeaponConfigs(), rtp::net::Player, rtp::ecs::components::Ammo::reloadTimer, rtp::log::warning(), rtp::Vec2< T >::x, and rtp::Vec2< T >::y.
createPowerupEntity()
ecs::Entity rtp::server::EntitySystem::createPowerupEntity (uint32_t roomId, const Vec2f & pos, ecs::components::PowerupType type, float value, float duration)
Create a new powerup entity in the ECS.
Parameters
roomId ID of the room the powerup belongs to
pos Position to spawn the powerup at
type Type of the powerup
value Value associated with the powerup
duration Duration the powerup effect lasts
Returns
The ID of the created powerup entity
Definition at line 277 of file EntitySystem.cpp.
References _registry, rtp::log::error(), rtp::ecs::Entity::index(), rtp::net::PowerupHeal, rtp::net::PowerupSpeed, rtp::ecs::components::Speed, rtp::Vec2< T >::x, and rtp::Vec2< T >::y.
update()
void rtp::server::EntitySystem::update (float dt) override virtual
Update movement system logic for one frame.
Parameters
dt Time elapsed since last update in seconds
Implements rtp::ecs::ISystem.
Definition at line 27 of file EntitySystem.cpp.
Member Data Documentation
_network
ServerNetwork& rtp::server::EntitySystem::_network protected
Reference to the server network manager.
Definition at line 141 of file EntitySystem.hpp.
Referenced by EntitySystem().
_networkSync
NetworkSyncSystem& rtp::server::EntitySystem::_networkSync protected
Reference to the network sync system.
Definition at line 142 of file EntitySystem.hpp.
Referenced by EntitySystem().
_registry
ecs::Registry& rtp::server::EntitySystem::_registry protected
Reference to the entity registry.
Definition at line 140 of file EntitySystem.hpp.
Referenced by EntitySystem(), applyWeaponToEntity(), createEnemyEntity(), createObstacleEntity(), createPlayerEntity(), and createPowerupEntity().
The documentation for this class was generated from the following files:
server/include/Systems/EntitySystem.hpp
server/src/Systems/EntitySystem.cpp