Air-Trap: client/src/main.cpp File Reference
main.cpp File Reference
#include "Core/Application.hpp"
Functions
std::string parseServerIp (int ac, char **av)
uint16_t parseServerPort (int ac, char **av)
int main (int ac, char **av)
Function Documentation
main()
int main (int ac, char ** av)
Definition at line 38 of file main.cpp.
References parseServerIp(), parseServerPort(), and rtp::client::Application::run().
parseServerIp()
std::string parseServerIp (int ac, char ** av)
Definition at line 10 of file main.cpp.
Referenced by main().
parseServerPort()
uint16_t parseServerPort (int ac, char ** av)
Definition at line 24 of file main.cpp.
Referenced by main().