Air-Trap: rtp::log::detail Namespace Reference
rtp::log::detail Namespace Reference
Classes
class LoggerBackend
Functions
void logImpl (Level level, std::string_view message, const std::source_location &loc)
static LoggerBackend & getBackend (void) noexcept
Function Documentation
getBackend()
LoggerBackend & rtp::log::detail::getBackend (void) static noexcept
Definition at line 131 of file Logger.cpp.
Referenced by rtp::log::configure(), and logImpl().
logImpl()
void rtp::log::detail::logImpl (Level level, std::string_view message, const std::source_location & loc)
Definition at line 137 of file Logger.cpp.
References getBackend(), and rtp::log::detail::LoggerBackend::write().