Air-Trap: rtp::log Namespace Reference
rtp::log Namespace Reference
Namespaces
namespace detail
Classes
struct LogFmt
Enumerations
enum class Level : std::uint8_t {
Debug = 0 , Info , Warning , Error ,
Fatal , None
}
Severity levels for log messages.
Functions
auto configure (std::string_view logFilePath) noexcept -> std::expected< void, rtp::Error >
Configure the logger using a configuration file.
template<typename... Args>
void debug (LogFmt< std::type_identity_t< Args >... > fmt, Args &&...args) noexcept
Log a debug message.
template<typename... Args>
void info (LogFmt< std::type_identity_t< Args >... > fmt, Args &&...args) noexcept
Log an informational message.
template<typename... Args>
void error (LogFmt< std::type_identity_t< Args >... > fmt, Args &&...args) noexcept
Log an error message.
template<typename... Args>
void warning (LogFmt< std::type_identity_t< Args >... > fmt, Args &&...args) noexcept
Log a warning message.
template<typename... Args>
void fatal (LogFmt< std::type_identity_t< Args >... > fmt, Args &&...args) noexcept
Log a fatal error message.
constexpr std::string_view toString (Level level) noexcept
Enumeration Type Documentation
Level
enum class rtp::log::Level : std::uint8_t strong
Severity levels for log messages.
Ordered from least to most severe. Each level represents a different category of log message importance.
Enumerator
Debug
Detailed information for debugging purposes.
Info
General informational messages.
Warning
Warning messages for potentially harmful situations.
Error
Error messages for error events.
Fatal
Fatal error messages indicating critical failures.
None
No logging (used to disable logging).
Definition at line 57 of file LogLevel.hpp.
Function Documentation
configure()
auto rtp::log::configure (std::string_view logFilePath) ->std::expected< void, rtp::Error > nodiscard noexcept
Configure the logger using a configuration file.
Parameters
logFilePath The path to the configuration file
Returns
std::expected<void, rtp::Error>
Note
If the configuration fails, returns an error message
Definition at line 153 of file Logger.cpp.
References rtp::Error::failure(), rtp::log::detail::getBackend(), rtp::InvalidParameter, rtp::log::detail::LoggerBackend::setOutputFile(), and rtp::Unknown.
debug()
template<typename... Args> void rtp::log::debug (LogFmt< std::type_identity_t< Args >... > fmt, Args &&... args) noexcept
Log a debug message.
Template Parameters
Args The types of the format arguments
Parameters
fmt The format string
args The format arguments
Referenced by rtp::server::CollisionSystem::despawn(), rtp::client::SpriteCustomizer::getSpriteInfo(), rtp::server::GameManager::handlePacket(), rtp::server::RoomSystem::launchReadyRooms(), rtp::client::NetworkSyncSystem::onEntityDeath(), rtp::client::NetworkSyncSystem::onSpawnEntityFromServer(), rtp::client::EntityBuilder::spawn(), and rtp::server::BoomerangSystem::update().
error()
template<typename... Args> void rtp::log::error (LogFmt< std::type_identity_t< Args >... > fmt, Args &&... args) noexcept
Log an error message.
Template Parameters
Args The types of the format arguments
Parameters
fmt The format string
args The format arguments
Referenced by rtp::server::GameManager::GameManager(), rtp::server::ServerNetwork::acceptConnection(), rtp::client::scenes::ModMenuScene::applyCustomSprite(), rtp::client::SpriteCustomizer::clearTextureCaches(), rtp::client::graphics::UiFactory::createButton(), rtp::client::graphics::UiFactory::createDropdown(), rtp::server::EntitySystem::createEnemyEntity(), rtp::server::EntitySystem::createObstacleEntity(), rtp::server::EntitySystem::createPlayerEntity(), rtp::server::EntitySystem::createPowerupEntity(), rtp::client::graphics::UiFactory::createSlider(), rtp::client::graphics::UiFactory::createSpritePreview(), rtp::client::graphics::UiFactory::createText(), rtp::client::graphics::UiFactory::createTextInput(), rtp::server::AuthSystem::handleLoginRequest(), rtp::server::GameManager::handlePlayerLoginAuth(), rtp::server::GameManager::handlePlayerRegisterAuth(), rtp::server::AuthSystem::handleRegisterRequest(), rtp::client::scenes::ModMenuScene::initializeModDirectory(), rtp::client::Application::initScenes(), rtp::server::RoomSystem::joinRoom(), rtp::client::Settings::loadFromClientJson(), rtp::client::TranslationManager::loadLanguage(), rtp::server::LevelSystem::loadLevel(), rtp::client::SpriteCustomizer::loadMappings(), rtp::client::AudioSystem::loadSoundBuffer(), rtp::client::scenes::ModMenuScene::loadSpriteMappings(), rtp::client::scenes::ModMenuScene::loadTexture(), rtp::client::NetworkSyncSystem::onBeamState(), rtp::client::NetworkSyncSystem::onSpawnEntityFromServer(), rtp::client::scenes::ModMenuScene::openFileDialog(), rtp::client::UISystem::playClickSound(), rtp::client::InputSystem::playShotSound(), rtp::client::ClientNetwork::readTcpHeader(), rtp::client::ClientNetwork::readUdp(), rtp::server::ServerNetwork::receiveUdpPacket(), rtp::client::scenes::GamepadSettingsScene::refreshButtonLabel(), rtp::client::scenes::KeyBindingScene::refreshButtonLabel(), rtp::client::systems::UIRenderSystem::renderButtons(), rtp::client::systems::UIRenderSystem::renderDropdowns(), rtp::client::systems::UIRenderSystem::renderSpritePreviews(), rtp::client::systems::UIRenderSystem::renderTextInputs(), rtp::client::systems::UIRenderSystem::renderTexts(), rtp::client::Settings::save(), rtp::client::scenes::ModMenuScene::saveSpriteMappings(), rtp::server::GameManager::sendEntitySpawnToSessions(), rtp::client::ClientNetwork::sendPacket(), rtp::client::scenes::ModMenuScene::showEntityCodex(), rtp::server::EnemyShootSystem::spawnBullet(), rtp::server::PlayerShootSystem::spawnBullet(), rtp::server::PlayerShootSystem::spawnChargedBullet(), rtp::server::PlayerShootSystem::spawnDebugPowerup(), rtp::server::LevelSystem::spawnEntityForRoom(), rtp::client::scenes::PlayingScene::spawnParallax(), rtp::server::CollisionSystem::spawnPowerup(), rtp::client::ClientNetwork::start(), rtp::server::ServerNetwork::start(), rtp::client::RenderSystem::update(), rtp::client::AudioSystem::updateAudioSources(), rtp::client::AudioSystem::updateSoundEvents(), and rtp::thread::ThreadPool::workerThread().
fatal()
template<typename... Args> void rtp::log::fatal (LogFmt< std::type_identity_t< Args >... > fmt, Args &&... args) noexcept
Log a fatal error message.
Template Parameters
Args The types of the format arguments
Parameters
fmt The format string
args The format arguments
Referenced by main().
info()
template<typename... Args> void rtp::log::info (LogFmt< std::type_identity_t< Args >... > fmt, Args &&... args) noexcept
Log an informational message.
Template Parameters
Args The types of the format arguments
Parameters
fmt The format string
args The format arguments
Referenced by rtp::server::GameManager::GameManager(), rtp::server::Room::Room(), rtp::server::RoomSystem::RoomSystem(), rtp::server::ServerNetwork::ServerNetwork(), rtp::client::Settings::Settings(), rtp::server::GameManager::~GameManager(), rtp::server::Room::~Room(), rtp::server::ServerNetwork::acceptConnection(), rtp::server::Room::addPlayer(), rtp::client::scenes::ModMenuScene::applyCustomSprite(), rtp::server::EntitySystem::applyWeaponToEntity(), rtp::client::scenes::LobbyScene::buildUi(), rtp::client::Application::changeState(), rtp::client::RenderSystem::clearTextureCache(), rtp::client::systems::UIRenderSystem::clearTextureCache(), rtp::client::SpriteCustomizer::clearTextureCaches(), rtp::thread::ThreadPool::create(), rtp::server::PlayerSystem::createPlayer(), rtp::server::RoomSystem::createRoom(), rtp::server::Room::forceFinishGame(), rtp::server::GameManager::handleCreateRoom(), rtp::server::NetworkSyncSystem::handleDisconnect(), rtp::client::NetworkSyncSystem::handleEvent(), rtp::client::scenes::GamepadSettingsScene::handleEvent(), rtp::client::scenes::KeyBindingScene::handleEvent(), rtp::server::NetworkSyncSystem::handleInput(), rtp::server::GameManager::handleLeaveRoom(), rtp::server::AuthSystem::handleLoginRequest(), rtp::client::UISystem::handleMouseClick(), rtp::server::GameManager::handlePacket(), rtp::server::GameManager::handlePlayerConnect(), rtp::server::NetworkSyncSystem::handlePlayerConnection(), rtp::server::GameManager::handlePlayerDisconnect(), rtp::server::GameManager::handlePlayerLoginAuth(), rtp::server::GameManager::handlePlayerRegisterAuth(), rtp::server::AuthSystem::handleRegisterRequest(), rtp::server::GameManager::handleSetReady(), rtp::server::GameManager::handleUpdateSelectedWeapon(), rtp::client::scenes::ModMenuScene::initializeModDirectory(), rtp::client::Application::initScenes(), rtp::client::Application::initUiECS(), rtp::client::Application::initUiSystems(), rtp::client::Application::initWorldECS(), rtp::client::Application::initWorldSystems(), rtp::server::RoomSystem::joinRoom(), rtp::server::RoomSystem::launchReadyRooms(), rtp::server::RoomSystem::listAllRooms(), rtp::client::Settings::loadFromClientJson(), rtp::client::TranslationManager::loadLanguage(), rtp::client::SpriteCustomizer::loadMappings(), rtp::client::scenes::ModMenuScene::loadSpriteMappings(), main(), rtp::client::NetworkSyncSystem::onCreateRoomResponse(), rtp::client::scenes::CreateRoomScene::onEnter(), rtp::client::scenes::GameOverScene::onEnter(), rtp::client::scenes::GamepadSettingsScene::onEnter(), rtp::client::scenes::KeyBindingScene::onEnter(), rtp::client::scenes::LobbyScene::onEnter(), rtp::client::scenes::LoginScene::onEnter(), rtp::client::scenes::MenuScene::onEnter(), rtp::client::scenes::ModMenuScene::onEnter(), rtp::client::scenes::PauseScene::onEnter(), rtp::client::scenes::PlayingScene::onEnter(), rtp::client::scenes::RoomWaitingScene::onEnter(), rtp::client::scenes::SettingsScene::onEnter(), rtp::client::NetworkSyncSystem::onEntityDeath(), rtp::client::scenes::CreateRoomScene::onExit(), rtp::client::scenes::GameOverScene::onExit(), rtp::client::scenes::LobbyScene::onExit(), rtp::client::scenes::LoginScene::onExit(), rtp::client::scenes::MenuScene::onExit(), rtp::client::scenes::ModMenuScene::onExit(), rtp::client::scenes::PauseScene::onExit(), rtp::client::NetworkSyncSystem::onJoinRoomResponse(), rtp::client::NetworkSyncSystem::onLeaveRoomResponse(), rtp::client::NetworkSyncSystem::onLoginResponse(), rtp::client::NetworkSyncSystem::onRegisterResponse(), rtp::client::NetworkSyncSystem::onRoomResponse(), rtp::client::NetworkSyncSystem::onSpawnEntityFromServer(), rtp::client::UISystem::playClickSound(), rtp::client::ClientNetwork::readTcpHeader(), rtp::server::ServerNetwork::receiveUdpPacket(), rtp::client::SpriteCustomizer::reloadMappings(), rtp::config::reloadWeaponConfigs(), rtp::server::PlayerSystem::removePlayer(), rtp::server::Room::removePlayer(), rtp::client::systems::UIRenderSystem::renderSpritePreviews(), rtp::client::NetworkSyncSystem::requestListRooms(), rtp::client::Settings::save(), rtp::client::scenes::ModMenuScene::saveSpriteMappings(), rtp::server::NetworkSyncSystem::sendPacketToEntity(), rtp::client::NetworkSyncSystem::sendSelectedWeapon(), rtp::client::ClientNetwork::sendUdpHandshake(), rtp::server::Room::setPlayerType(), rtp::client::Application::setupSettingsCallbacks(), rtp::server::signal_handler(), rtp::client::EntityBuilder::spawn(), rtp::server::CollisionSystem::spawnPowerup(), rtp::client::ClientNetwork::start(), rtp::server::ServerNetwork::start(), rtp::server::Room::startGame(), rtp::server::startGame(), rtp::server::LevelSystem::startLevelForRoom(), rtp::client::ClientNetwork::stop(), rtp::server::ServerNetwork::stop(), rtp::client::NetworkSyncSystem::tryCreateRoom(), rtp::client::InputSystem::update(), rtp::client::ShieldSystem::update(), rtp::server::BoomerangSystem::update(), rtp::server::CollisionSystem::update(), rtp::server::PlayerShootSystem::update(), rtp::server::PlayerSystem::updatePlayerUsername(), and rtp::client::AudioSystem::updateSoundEvents().
toString()
std::string_view rtp::log::toString (Level level) constexpr noexcept
Referenced by std::formatter< rtp::log::Level >::format().
warning()
template<typename... Args> void rtp::log::warning (LogFmt< std::type_identity_t< Args >... > fmt, Args &&... args) noexcept
Log a warning message.
Template Parameters
Args The types of the format arguments
Parameters
fmt The format string
args The format arguments
Referenced by rtp::client::Settings::Settings(), rtp::sys::DynamicLibrary::~DynamicLibrary(), rtp::server::Room::addPlayer(), rtp::server::EntitySystem::applyWeaponToEntity(), rtp::client::Application::changeState(), rtp::client::graphics::UiFactory::createDropdown(), rtp::server::PlayerSystem::createPlayer(), rtp::server::EntitySystem::createPlayerEntity(), rtp::server::Room::forceFinishGame(), rtp::client::TranslationManager::get(), rtp::server::Room::getPlayerType(), rtp::client::NetworkSyncSystem::handleEvent(), rtp::server::AuthSystem::handleLoginRequest(), rtp::server::AuthSystem::handleRegisterRequest(), rtp::server::GameManager::handleUpdateSelectedWeapon(), rtp::server::RoomSystem::joinRoom(), rtp::server::LevelSystem::loadLevel(), rtp::client::SpriteCustomizer::loadMappings(), rtp::client::NetworkSyncSystem::onCreateRoomResponse(), rtp::client::scenes::PlayingScene::onEnter(), rtp::client::NetworkSyncSystem::onEntityDeath(), rtp::client::NetworkSyncSystem::onJoinRoomResponse(), rtp::client::NetworkSyncSystem::onLeaveRoomResponse(), rtp::client::NetworkSyncSystem::onLoginResponse(), rtp::client::NetworkSyncSystem::onRegisterResponse(), rtp::client::NetworkSyncSystem::onSpawnEntityFromServer(), rtp::sys::DynamicLibrary::operator=(), rtp::client::scenes::GamepadSettingsScene::refreshButtonLabel(), rtp::client::scenes::KeyBindingScene::refreshButtonLabel(), rtp::server::Room::removePlayer(), rtp::server::NetworkSyncSystem::sendPacketToEntity(), rtp::server::Room::setPlayerType(), rtp::server::Room::startGame(), rtp::server::CollisionSystem::update(), and rtp::client::scenes::MenuScene::updateWeaponDisplay().