Air-Trap: rtp::config Namespace Reference
rtp::config Namespace Reference
File : SpriteMapConfig.hpp License: MIT Author : GitHub Copilot Date : 18/01/2026.
Classes
class SimpleJson
Functions
std::unordered_map< std::string, SimpleJson > parseWeaponsFile (const std::string &filepath="config/common/weapons.json")
std::unordered_map< std::string, std::string > loadSpriteMappings (const std::string &filepath="config/client/sprite_mappings.json")
Load sprite mappings from a JSON file.
bool saveSpriteMappings (const std::unordered_map< std::string, std::string > &mappings, const std::string &filepath="config/client/sprite_mappings.json")
Save sprite mappings to a JSON file.
std::unordered_map< rtp::ecs::components::WeaponKind, rtp::ecs::components::SimpleWeapon > loadWeaponConfigs (const std::string &path="config/common/weapons.json")
std::unordered_map< rtp::ecs::components::WeaponKind, rtp::ecs::components::SimpleWeapon > & weapon_cache ()
bool & weapon_cache_loaded ()
void reloadWeaponConfigs ()
const rtp::ecs::components::SimpleWeapon & getWeaponDef (rtp::ecs::components::WeaponKind kind)
bool hasWeaponConfigs ()
std::string getWeaponDisplayName (rtp::ecs::components::WeaponKind kind)
Detailed Description
File : SpriteMapConfig.hpp License: MIT Author : GitHub Copilot Date : 18/01/2026.
Configuration loader for sprite mappings (mod system)
Function Documentation
getWeaponDef()
const rtp::ecs::components::SimpleWeapon & rtp::config::getWeaponDef (rtp::ecs::components::WeaponKind kind) inline
Definition at line 95 of file WeaponConfig.hpp.
References loadWeaponConfigs(), weapon_cache(), and weapon_cache_loaded().
Referenced by rtp::server::EntitySystem::applyWeaponToEntity(), rtp::server::EntitySystem::createPlayerEntity(), rtp::client::NetworkSyncSystem::onSpawnEntityFromServer(), and rtp::client::scenes::MenuScene::updateWeaponDisplay().
getWeaponDisplayName()
std::string rtp::config::getWeaponDisplayName (rtp::ecs::components::WeaponKind kind) inline
Definition at line 119 of file WeaponConfig.hpp.
References parseWeaponsFile().
Referenced by rtp::client::Settings::getWeaponName(), rtp::client::scenes::MenuScene::onEnter(), and rtp::client::scenes::MenuScene::updateWeaponDisplay().
hasWeaponConfigs()
bool rtp::config::hasWeaponConfigs () inline
Definition at line 110 of file WeaponConfig.hpp.
References loadWeaponConfigs(), weapon_cache(), and weapon_cache_loaded().
Referenced by rtp::server::EntitySystem::applyWeaponToEntity(), rtp::server::EntitySystem::createPlayerEntity(), rtp::client::Settings::getWeaponName(), rtp::client::scenes::MenuScene::onEnter(), rtp::client::NetworkSyncSystem::onSpawnEntityFromServer(), and rtp::client::scenes::MenuScene::updateWeaponDisplay().
loadSpriteMappings()
std::unordered_map< std::string, std::string > rtp::config::loadSpriteMappings (const std::string & filepath = "config/client/sprite_mappings.json") inline
Load sprite mappings from a JSON file.
Parameters
filepath Path to sprite_mappings.json (default: config/client/sprite_mappings.json)
Returns
Map of entity keys to sprite paths
Definition at line 26 of file SpriteMapConfig.hpp.
References rtp::config::SimpleJson::getData(), and rtp::config::SimpleJson::parseContent().
Referenced by rtp::client::SpriteCustomizer::loadMappings(), and rtp::client::scenes::ModMenuScene::loadSpriteMappings().
loadWeaponConfigs()
std::unordered_map< rtp::ecs::components::WeaponKind, rtp::ecs::components::SimpleWeapon > rtp::config::loadWeaponConfigs (const std::string & path = "config/common/weapons.json") inline
Definition at line 15 of file WeaponConfig.hpp.
References rtp::ecs::components::SimpleWeapon::ammo, rtp::ecs::components::Beam, rtp::ecs::components::SimpleWeapon::beamCooldown, rtp::ecs::components::SimpleWeapon::beamDuration, rtp::ecs::components::Boomerang, rtp::ecs::components::Classic, rtp::ecs::components::SimpleWeapon::damage, rtp::ecs::components::SimpleWeapon::difficulty, rtp::ecs::components::SimpleWeapon::fireRate, rtp::ecs::components::SimpleWeapon::homing, rtp::ecs::components::SimpleWeapon::homingRange, rtp::ecs::components::SimpleWeapon::homingSteering, rtp::ecs::components::SimpleWeapon::isBoomerang, rtp::ecs::components::SimpleWeapon::kind, rtp::ecs::components::SimpleWeapon::lastShotTime, rtp::ecs::components::SimpleWeapon::maxAmmo, parseWeaponsFile(), and rtp::ecs::components::Tracker.
Referenced by getWeaponDef(), hasWeaponConfigs(), and reloadWeaponConfigs().
parseWeaponsFile()
std::unordered_map< std::string, SimpleJson > rtp::config::parseWeaponsFile (const std::string & filepath = "config/common/weapons.json") inline
Definition at line 169 of file SimpleJsonParser.hpp.
References rtp::config::SimpleJson::parseContent().
Referenced by getWeaponDisplayName(), and loadWeaponConfigs().
reloadWeaponConfigs()
void rtp::config::reloadWeaponConfigs () inline
Definition at line 88 of file WeaponConfig.hpp.
References rtp::log::info(), loadWeaponConfigs(), weapon_cache(), and weapon_cache_loaded().
Referenced by rtp::client::scenes::MenuScene::onEnter().
saveSpriteMappings()
bool rtp::config::saveSpriteMappings (const std::unordered_map< std::string, std::string > & mappings, const std::string & filepath = "config/client/sprite_mappings.json") inline
Save sprite mappings to a JSON file.
Parameters
mappings Map of entity keys to sprite paths
filepath Path to sprite_mappings.json (default: config/client/sprite_mappings.json)
Returns
true if saved successfully, false otherwise
Definition at line 54 of file SpriteMapConfig.hpp.
Referenced by rtp::client::scenes::ModMenuScene::saveSpriteMappings().
weapon_cache()
std::unordered_map< rtp::ecs::components::WeaponKind, rtp::ecs::components::SimpleWeapon > & rtp::config::weapon_cache () inline
Definition at line 76 of file WeaponConfig.hpp.
Referenced by getWeaponDef(), hasWeaponConfigs(), and reloadWeaponConfigs().
weapon_cache_loaded()
bool & rtp::config::weapon_cache_loaded () inline
Definition at line 82 of file WeaponConfig.hpp.
Referenced by getWeaponDef(), hasWeaponConfigs(), and reloadWeaponConfigs().