Air-Trap: std::formatter< rtp::Error > Struct Reference
std::formatter< rtp::Error > Struct Reference
Formatter specialization for Error objects.
#include <Error.hpp>
Public Member Functions
auto format (const rtp::Error &e, format_context &ctx) const
Format an Error object.
Detailed Description
Formatter specialization for Error objects.
Allows Error objects to be used with std::format and std::print.
Definition at line 259 of file Error.hpp.
Member Function Documentation
format()
auto std::formatter< rtp::Error >::format (const rtp::Error & e, format_context & ctx) const inline
Format an Error object.
Parameters
e The error to format
ctx The format context
Returns
Iterator to the end of the formatted output
Definition at line 266 of file Error.hpp.
References rtp::Error::code(), rtp::Error::message(), rtp::Error::severity(), and rtp::toString().
The documentation for this struct was generated from the following file:
common/include/RType/Error.hpp