Air-Trap: rtp::client::EntityTemplate Struct Reference
rtp::client::EntityTemplate Struct Reference
#include <EntityBuilder.hpp>
Classes
struct SpriteAnimDef
struct ParallaxDef
Static Public Member Functions
static EntityTemplate makeFromDef (const Vec2f &initialPos, const SpriteAnimDef &d)
static EntityTemplate makeParallax (const ParallaxDef &p)
static EntityTemplate createParrallaxLvl1_1 ()
static EntityTemplate createParrallaxLvl1_2 ()
static EntityTemplate createParallaxLvl2_1 ()
static EntityTemplate createParallaxLvl2_2 ()
static EntityTemplate createParallaxLvl2_3 ()
static EntityTemplate createParallaxLvl2_4 ()
static EntityTemplate createParallaxLvl2_5 ()
static EntityTemplate createParallaxLvl2_6 ()
static EntityTemplate createParallaxLvl3_1 ()
static EntityTemplate createParallaxLvl3_2 ()
static EntityTemplate createParallaxLvl3_3 ()
static EntityTemplate createParallaxLvl3_4 ()
static EntityTemplate createParallaxLvl3_5 ()
static EntityTemplate createParallaxLvl3_6 ()
static EntityTemplate createParallaxLvl3_7 ()
static EntityTemplate createParallaxLvl3_8 ()
static EntityTemplate createParallaxLvl3_9 ()
static EntityTemplate createParallaxLvl4_1 ()
static EntityTemplate createParallaxLvl4_2 ()
static EntityTemplate createParallaxLvl4_3 ()
static EntityTemplate createParallaxLvl4_4 ()
static EntityTemplate createParallaxLvl4_5 ()
static EntityTemplate createParallaxLvl4_6 ()
static EntityTemplate player_ship (const Vec2f &initialPos)
static EntityTemplate shot_insane (const Vec2f &initialPos)
static EntityTemplate effect_1 (const Vec2f &initialPos)
static EntityTemplate shot_1 (const Vec2f &initialPos)
static EntityTemplate shot_2 (const Vec2f &initialPos)
static EntityTemplate shot_3 (const Vec2f &initialPos)
static EntityTemplate shot_4 (const Vec2f &initialPos)
static EntityTemplate shot_5 (const Vec2f &initialPos)
static EntityTemplate effect_2 (const Vec2f &initialPos)
static EntityTemplate effect_3 (const Vec2f &initialPos)
static EntityTemplate enemy_1 (const Vec2f &initialPos)
static EntityTemplate shot_6 (const Vec2f &initialPos)
static EntityTemplate enemy_2 (const Vec2f &initialPos)
static EntityTemplate shot_7 (const Vec2f &initialPos)
static EntityTemplate effect_4 (const Vec2f &initialPos)
static EntityTemplate effect_5 (const Vec2f &initialPos)
static EntityTemplate createBulletPlayer (const Vec2f &initialPos)
static EntityTemplate createBulletEnemy (const Vec2f &initialPos)
static EntityTemplate createBasicScout2 (const Vec2f &initialPos)
static EntityTemplate createPowerUpHeal (const Vec2f &initialPos)
static EntityTemplate createPowerUpDoubleFire (const Vec2f &initialPos)
static EntityTemplate createPowerUpShield (const Vec2f &initialPos)
static EntityTemplate createBossShip (const Vec2f &initialPos)
static EntityTemplate createBossShield (const Vec2f &initialPos)
static EntityTemplate createBoss2Kraken (const Vec2f &initialPos)
static EntityTemplate createBoss2Bullet (const Vec2f &initialPos)
Public Attributes
std::string id
Enemy type identifier.
std::string tag {}
Template tag for entity differentiation.
Vec2f position {0.0f, 0.0f}
Spawn position.
float rotation {0.0f}
Spawn rotation.
Vec2f scale {1.0f, 1.0f}
Spawn scale.
bool withVelocity {false}
Whether to add Velocity component.
ecs::components::Velocity velocity {}
Initial velocity.
ecs::components::Sprite sprite {}
Sprite data.
bool withAnimation
Whether to add Animation component.
ecs::components::Animation animation {}
Initial animation data.
bool withParallax
Whether to add ParallaxLayer component.
ecs::components::ParallaxLayer parallax {}
Parallax layer data.
Static Public Attributes
static constexpr ParallaxDef kParallaxLvl1_1 { "assets/backgrounds/lvl1/stars_far.png", 10.0f, {-50.0f, 0.0f}, 200, 100.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 }
static constexpr ParallaxDef kParallaxLvl1_2 { "assets/backgrounds/lvl1/stars_near.png", 20.0f, {-50.0f, 0.0f}, 255, 300.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 }
static constexpr ParallaxDef kParallaxLvl2_1 { "assets/backgrounds/lvl2/moon_back.png", 10.0f, {0.0f, 0.0f}, 200, 80.0f, 1200.0f, {1.0f, 1.0f}, 1300, 720 }
static constexpr ParallaxDef kParallaxLvl2_2 { "assets/backgrounds/lvl2/moon_earth.png", 25.0f, {-30.0f, 0.0f}, 255, 150.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 }
static constexpr ParallaxDef kParallaxLvl2_3 { "assets/backgrounds/lvl2/moon_floor.png", 12.0f, {-20.0f, 0.0f}, 200, 60.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 }
static constexpr ParallaxDef kParallaxLvl2_4 { "assets/backgrounds/lvl2/moon_front.png", 18.0f, {-40.0f, 0.0f}, 200, 90.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 }
static constexpr ParallaxDef kParallaxLvl2_5 { "assets/backgrounds/lvl2/moon_mid.png", 20.0f, {-25.0f, 0.0f}, 255, 70.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 }
static constexpr ParallaxDef kParallaxLvl2_6 { "assets/backgrounds/lvl2/moon_sky.png", 10.0f, {-15.0f, 0.0f}, 200, 50.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 }
static constexpr ParallaxDef kParallaxLvl3_1 { "assets/backgrounds/lvl3/Sky_back_mountain.png", 15.0f, {-20.0f, 0.0f}, 255, 60.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 }
static constexpr ParallaxDef kParallaxLvl3_2 { "assets/backgrounds/lvl3/sky_cloud_floor_2.png", 22.0f, {-35.0f, 0.0f}, 200, 85.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 }
static constexpr ParallaxDef kParallaxLvl3_3 { "assets/backgrounds/lvl3/sky_cloud_floor.png", 18.0f, {-25.0f, 0.0f}, 255, 70.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 }
static constexpr ParallaxDef kParallaxLvl3_4 { "assets/backgrounds/lvl3/Sky_cloud_single.png", 20.0f, {-30.0f, 0.0f}, 255, 90.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 }
static constexpr ParallaxDef kParallaxLvl3_5 { "assets/backgrounds/lvl3/sky_clouds.png", 12.0f, {-15.0f, 0.0f}, 200, 55.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 }
static constexpr ParallaxDef kParallaxLvl3_6 { "assets/backgrounds/lvl3/Sky_front_cloud.png", 12.0f, {-15.0f, 0.0f}, 200, 55.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 }
static constexpr ParallaxDef kParallaxLvl3_7 { "assets/backgrounds/lvl3/sky_front_mountain.png", 12.0f, {-15.0f, 0.0f}, 200, 55.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 }
static constexpr ParallaxDef kParallaxLvl3_8 { "assets/backgrounds/lvl3/sky_moon.png", 12.0f, {-15.0f, 0.0f}, 200, 55.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 }
static constexpr ParallaxDef kParallaxLvl3_9 { "assets/backgrounds/lvl3/Sky_sky.png", 12.0f, {-15.0f, 0.0f}, 200, 55.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 }
static constexpr ParallaxDef kParallaxLvl4_1 { "assets/backgrounds/lvl4/desert_cloud.png", 15.0f, {-30.0f, 0.0f}, 200, 80.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 }
static constexpr ParallaxDef kParallaxLvl4_2 { "assets/backgrounds/lvl4/desert_dunefrontt.png", 25.0f, {-30.0f, 0.0f}, 255, 150.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 }
static constexpr ParallaxDef kParallaxLvl4_3 { "assets/backgrounds/lvl4/desert_dunemid.png", 12.0f, {-20.0f, 0.0f}, 200, 60.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 }
static constexpr ParallaxDef kParallaxLvl4_4 { "assets/backgrounds/lvl4/desert_moon.png", 18.0f, {-40.0f, 0.0f}, 200, 90.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 }
static constexpr ParallaxDef kParallaxLvl4_5 { "assets/backgrounds/lvl4/desert_mountain.png", 20.0f, {-25.0f, 0.0f}, 255, 70.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 }
static constexpr ParallaxDef kParallaxLvl4_6 { "assets/backgrounds/lvl4/desert_sky.png", 10.0f, {-15.0f, 0.0f}, 200, 50.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 }
static constexpr SpriteAnimDef k_rt1_1
static constexpr SpriteAnimDef k_rt1_2
static constexpr SpriteAnimDef k_rt1_3
static constexpr SpriteAnimDef k_rt1_4
static constexpr SpriteAnimDef k_rt1_5
static constexpr SpriteAnimDef k_rt1_6
static constexpr SpriteAnimDef k_rt1_7
static constexpr SpriteAnimDef k_rt1_8
static constexpr SpriteAnimDef k_rt1_12
static constexpr SpriteAnimDef k_rt1_13
static constexpr SpriteAnimDef k_rt2_2
static constexpr SpriteAnimDef k_rt2_3
static constexpr SpriteAnimDef k_rt2_4
static constexpr SpriteAnimDef k_rt2_5
static constexpr SpriteAnimDef k_rt2_6
static constexpr SpriteAnimDef k_rt2_7
static constexpr SpriteAnimDef k_rt3_1
static constexpr SpriteAnimDef k_rt3_2
static constexpr SpriteAnimDef k_rt3_3
static constexpr SpriteAnimDef k_rt39_1
static constexpr SpriteAnimDef k_rt39_2
static constexpr SpriteAnimDef k_rt35_boss2
static constexpr SpriteAnimDef k_rt35_boss2_bullet
Detailed Description
Definition at line 32 of file EntityBuilder.hpp.
Member Function Documentation
createBasicScout2()
EntityTemplate rtp::client::EntityTemplate::createBasicScout2 (const Vec2f & initialPos) inline static
Definition at line 650 of file EntityBuilder.hpp.
References k_rt2_2, and makeFromDef().
createBoss2Bullet()
EntityTemplate rtp::client::EntityTemplate::createBoss2Bullet (const Vec2f & initialPos) inline static
Definition at line 687 of file EntityBuilder.hpp.
References k_rt35_boss2_bullet, and makeFromDef().
Referenced by rtp::client::NetworkSyncSystem::onSpawnEntityFromServer().
createBoss2Kraken()
EntityTemplate rtp::client::EntityTemplate::createBoss2Kraken (const Vec2f & initialPos) inline static
Definition at line 680 of file EntityBuilder.hpp.
References k_rt35_boss2, and makeFromDef().
Referenced by rtp::client::NetworkSyncSystem::onSpawnEntityFromServer().
createBossShield()
EntityTemplate rtp::client::EntityTemplate::createBossShield (const Vec2f & initialPos) inline static
Definition at line 675 of file EntityBuilder.hpp.
References k_rt39_2, and makeFromDef().
Referenced by rtp::client::NetworkSyncSystem::onSpawnEntityFromServer().
createBossShip()
EntityTemplate rtp::client::EntityTemplate::createBossShip (const Vec2f & initialPos) inline static
Definition at line 670 of file EntityBuilder.hpp.
References k_rt39_1, and makeFromDef().
Referenced by rtp::client::NetworkSyncSystem::onSpawnEntityFromServer().
createBulletEnemy()
EntityTemplate rtp::client::EntityTemplate::createBulletEnemy (const Vec2f & initialPos) inline static
Definition at line 643 of file EntityBuilder.hpp.
References k_rt2_3, and makeFromDef().
Referenced by rtp::client::NetworkSyncSystem::onSpawnEntityFromServer().
createBulletPlayer()
EntityTemplate rtp::client::EntityTemplate::createBulletPlayer (const Vec2f & initialPos) inline static
Definition at line 636 of file EntityBuilder.hpp.
References k_rt2_3, and makeFromDef().
Referenced by rtp::client::NetworkSyncSystem::onSpawnEntityFromServer().
createParallaxLvl2_1()
EntityTemplate rtp::client::EntityTemplate::createParallaxLvl2_1 () inline static
Definition at line 447 of file EntityBuilder.hpp.
References kParallaxLvl2_1, and makeParallax().
Referenced by rtp::client::scenes::PlayingScene::spawnParallax().
createParallaxLvl2_2()
EntityTemplate rtp::client::EntityTemplate::createParallaxLvl2_2 () inline static
Definition at line 452 of file EntityBuilder.hpp.
References kParallaxLvl2_2, and makeParallax().
createParallaxLvl2_3()
EntityTemplate rtp::client::EntityTemplate::createParallaxLvl2_3 () inline static
Definition at line 457 of file EntityBuilder.hpp.
References kParallaxLvl2_3, and makeParallax().
createParallaxLvl2_4()
EntityTemplate rtp::client::EntityTemplate::createParallaxLvl2_4 () inline static
Definition at line 462 of file EntityBuilder.hpp.
References kParallaxLvl2_4, and makeParallax().
createParallaxLvl2_5()
EntityTemplate rtp::client::EntityTemplate::createParallaxLvl2_5 () inline static
Definition at line 467 of file EntityBuilder.hpp.
References kParallaxLvl2_5, and makeParallax().
createParallaxLvl2_6()
EntityTemplate rtp::client::EntityTemplate::createParallaxLvl2_6 () inline static
Definition at line 472 of file EntityBuilder.hpp.
References kParallaxLvl2_6, and makeParallax().
createParallaxLvl3_1()
EntityTemplate rtp::client::EntityTemplate::createParallaxLvl3_1 () inline static
Definition at line 477 of file EntityBuilder.hpp.
References kParallaxLvl3_1, and makeParallax().
Referenced by rtp::client::scenes::PlayingScene::spawnParallax().
createParallaxLvl3_2()
EntityTemplate rtp::client::EntityTemplate::createParallaxLvl3_2 () inline static
Definition at line 482 of file EntityBuilder.hpp.
References kParallaxLvl3_2, and makeParallax().
Referenced by rtp::client::scenes::PlayingScene::spawnParallax().
createParallaxLvl3_3()
EntityTemplate rtp::client::EntityTemplate::createParallaxLvl3_3 () inline static
Definition at line 487 of file EntityBuilder.hpp.
References kParallaxLvl3_3, and makeParallax().
Referenced by rtp::client::scenes::PlayingScene::spawnParallax().
createParallaxLvl3_4()
EntityTemplate rtp::client::EntityTemplate::createParallaxLvl3_4 () inline static
Definition at line 492 of file EntityBuilder.hpp.
References kParallaxLvl3_4, and makeParallax().
Referenced by rtp::client::scenes::PlayingScene::spawnParallax().
createParallaxLvl3_5()
EntityTemplate rtp::client::EntityTemplate::createParallaxLvl3_5 () inline static
Definition at line 497 of file EntityBuilder.hpp.
References kParallaxLvl3_5, and makeParallax().
Referenced by rtp::client::scenes::PlayingScene::spawnParallax().
createParallaxLvl3_6()
EntityTemplate rtp::client::EntityTemplate::createParallaxLvl3_6 () inline static
Definition at line 502 of file EntityBuilder.hpp.
References kParallaxLvl3_6, and makeParallax().
Referenced by rtp::client::scenes::PlayingScene::spawnParallax().
createParallaxLvl3_7()
EntityTemplate rtp::client::EntityTemplate::createParallaxLvl3_7 () inline static
Definition at line 507 of file EntityBuilder.hpp.
References kParallaxLvl3_7, and makeParallax().
Referenced by rtp::client::scenes::PlayingScene::spawnParallax().
createParallaxLvl3_8()
EntityTemplate rtp::client::EntityTemplate::createParallaxLvl3_8 () inline static
Definition at line 512 of file EntityBuilder.hpp.
References kParallaxLvl3_8, and makeParallax().
Referenced by rtp::client::scenes::PlayingScene::spawnParallax().
createParallaxLvl3_9()
EntityTemplate rtp::client::EntityTemplate::createParallaxLvl3_9 () inline static
Definition at line 517 of file EntityBuilder.hpp.
References kParallaxLvl3_9, and makeParallax().
Referenced by rtp::client::scenes::PlayingScene::spawnParallax().
createParallaxLvl4_1()
EntityTemplate rtp::client::EntityTemplate::createParallaxLvl4_1 () inline static
Definition at line 522 of file EntityBuilder.hpp.
References kParallaxLvl4_1, and makeParallax().
Referenced by rtp::client::scenes::PlayingScene::spawnParallax().
createParallaxLvl4_2()
EntityTemplate rtp::client::EntityTemplate::createParallaxLvl4_2 () inline static
Definition at line 527 of file EntityBuilder.hpp.
References kParallaxLvl4_2, and makeParallax().
Referenced by rtp::client::scenes::PlayingScene::spawnParallax().
createParallaxLvl4_3()
EntityTemplate rtp::client::EntityTemplate::createParallaxLvl4_3 () inline static
Definition at line 532 of file EntityBuilder.hpp.
References kParallaxLvl4_3, and makeParallax().
Referenced by rtp::client::scenes::PlayingScene::spawnParallax().
createParallaxLvl4_4()
EntityTemplate rtp::client::EntityTemplate::createParallaxLvl4_4 () inline static
Definition at line 537 of file EntityBuilder.hpp.
References kParallaxLvl4_4, and makeParallax().
Referenced by rtp::client::scenes::PlayingScene::spawnParallax().
createParallaxLvl4_5()
EntityTemplate rtp::client::EntityTemplate::createParallaxLvl4_5 () inline static
Definition at line 542 of file EntityBuilder.hpp.
References kParallaxLvl4_5, and makeParallax().
Referenced by rtp::client::scenes::PlayingScene::spawnParallax().
createParallaxLvl4_6()
EntityTemplate rtp::client::EntityTemplate::createParallaxLvl4_6 () inline static
Definition at line 547 of file EntityBuilder.hpp.
References kParallaxLvl4_6, and makeParallax().
Referenced by rtp::client::scenes::PlayingScene::spawnParallax().
createParrallaxLvl1_1()
EntityTemplate rtp::client::EntityTemplate::createParrallaxLvl1_1 () inline static
Definition at line 437 of file EntityBuilder.hpp.
References kParallaxLvl1_1, and makeParallax().
Referenced by rtp::client::scenes::MenuScene::onEnter(), and rtp::client::scenes::PlayingScene::spawnParallax().
createParrallaxLvl1_2()
EntityTemplate rtp::client::EntityTemplate::createParrallaxLvl1_2 () inline static
Definition at line 442 of file EntityBuilder.hpp.
References kParallaxLvl1_2, and makeParallax().
Referenced by rtp::client::scenes::MenuScene::onEnter(), and rtp::client::scenes::PlayingScene::spawnParallax().
createPowerUpDoubleFire()
EntityTemplate rtp::client::EntityTemplate::createPowerUpDoubleFire (const Vec2f & initialPos) inline static
Definition at line 660 of file EntityBuilder.hpp.
References k_rt3_2, and makeFromDef().
Referenced by rtp::client::NetworkSyncSystem::onSpawnEntityFromServer().
createPowerUpHeal()
EntityTemplate rtp::client::EntityTemplate::createPowerUpHeal (const Vec2f & initialPos) inline static
Definition at line 655 of file EntityBuilder.hpp.
References k_rt3_1, and makeFromDef().
Referenced by rtp::client::NetworkSyncSystem::onSpawnEntityFromServer().
createPowerUpShield()
EntityTemplate rtp::client::EntityTemplate::createPowerUpShield (const Vec2f & initialPos) inline static
Definition at line 665 of file EntityBuilder.hpp.
References k_rt3_3, and makeFromDef().
Referenced by rtp::client::NetworkSyncSystem::onSpawnEntityFromServer().
effect_1()
EntityTemplate rtp::client::EntityTemplate::effect_1 (const Vec2f & initialPos) inline static
Definition at line 562 of file EntityBuilder.hpp.
References k_rt1_3, and makeFromDef().
Referenced by rtp::client::NetworkSyncSystem::onSpawnEntityFromServer().
effect_2()
EntityTemplate rtp::client::EntityTemplate::effect_2 (const Vec2f & initialPos) inline static
Definition at line 595 of file EntityBuilder.hpp.
References k_rt1_12, and makeFromDef().
effect_3()
EntityTemplate rtp::client::EntityTemplate::effect_3 (const Vec2f & initialPos) inline static
Definition at line 600 of file EntityBuilder.hpp.
References k_rt1_13, and makeFromDef().
effect_4()
EntityTemplate rtp::client::EntityTemplate::effect_4 (const Vec2f & initialPos) inline static
Definition at line 625 of file EntityBuilder.hpp.
References k_rt2_6, and makeFromDef().
Referenced by rtp::client::NetworkSyncSystem::onSpawnEntityFromServer().
effect_5()
EntityTemplate rtp::client::EntityTemplate::effect_5 (const Vec2f & initialPos) inline static
Definition at line 630 of file EntityBuilder.hpp.
References k_rt2_7, and makeFromDef().
enemy_1()
EntityTemplate rtp::client::EntityTemplate::enemy_1 (const Vec2f & initialPos) inline static
Definition at line 605 of file EntityBuilder.hpp.
References k_rt2_2, and makeFromDef().
Referenced by rtp::client::scenes::MenuScene::onEnter(), and rtp::client::NetworkSyncSystem::onSpawnEntityFromServer().
enemy_2()
EntityTemplate rtp::client::EntityTemplate::enemy_2 (const Vec2f & initialPos) inline static
Definition at line 615 of file EntityBuilder.hpp.
References k_rt2_4, and makeFromDef().
Referenced by rtp::client::scenes::MenuScene::onEnter(), and rtp::client::NetworkSyncSystem::onSpawnEntityFromServer().
makeFromDef()
EntityTemplate rtp::client::EntityTemplate::makeFromDef (const Vec2f & initialPos, const SpriteAnimDef & d) inline static
Definition at line 92 of file EntityBuilder.hpp.
References animation, rtp::client::EntityTemplate::SpriteAnimDef::blue, rtp::ecs::components::Sprite::blue, rtp::client::EntityTemplate::SpriteAnimDef::direction, rtp::ecs::components::Velocity::direction, rtp::client::EntityTemplate::SpriteAnimDef::frameHeight, rtp::ecs::components::Animation::frameHeight, rtp::client::EntityTemplate::SpriteAnimDef::frameLeft, rtp::ecs::components::Animation::frameLeft, rtp::client::EntityTemplate::SpriteAnimDef::frameTop, rtp::ecs::components::Animation::frameTop, rtp::client::EntityTemplate::SpriteAnimDef::frameWidth, rtp::ecs::components::Animation::frameWidth, rtp::client::EntityTemplate::SpriteAnimDef::green, rtp::ecs::components::Sprite::green, id, rtp::client::EntityTemplate::SpriteAnimDef::id, position, rtp::client::EntityTemplate::SpriteAnimDef::rectHeight, rtp::ecs::components::Sprite::rectHeight, rtp::client::EntityTemplate::SpriteAnimDef::rectLeft, rtp::ecs::components::Sprite::rectLeft, rtp::client::EntityTemplate::SpriteAnimDef::rectTop, rtp::ecs::components::Sprite::rectTop, rtp::client::EntityTemplate::SpriteAnimDef::rectWidth, rtp::ecs::components::Sprite::rectWidth, rtp::client::EntityTemplate::SpriteAnimDef::red, rtp::ecs::components::Sprite::red, rotation, scale, rtp::client::EntityTemplate::SpriteAnimDef::scale, rtp::client::EntityTemplate::SpriteAnimDef::speed, rtp::ecs::components::Velocity::speed, sprite, rtp::client::EntityTemplate::SpriteAnimDef::texturePath, rtp::ecs::components::Sprite::texturePath, rtp::client::EntityTemplate::SpriteAnimDef::totalFrames, rtp::ecs::components::Animation::totalFrames, velocity, rtp::client::EntityTemplate::SpriteAnimDef::withAnimation, withAnimation, withVelocity, rtp::client::EntityTemplate::SpriteAnimDef::zIndex, and rtp::ecs::components::Sprite::zIndex.
Referenced by createBasicScout2(), createBoss2Bullet(), createBoss2Kraken(), createBossShield(), createBossShip(), createBulletEnemy(), createBulletPlayer(), createPowerUpDoubleFire(), createPowerUpHeal(), createPowerUpShield(), effect_1(), effect_2(), effect_3(), effect_4(), effect_5(), enemy_1(), enemy_2(), player_ship(), shot_1(), shot_2(), shot_3(), shot_4(), shot_5(), shot_6(), shot_7(), and shot_insane().
makeParallax()
EntityTemplate rtp::client::EntityTemplate::makeParallax (const ParallaxDef & p) inline static
Definition at line 127 of file EntityBuilder.hpp.
References rtp::ecs::components::Velocity::direction, id, rtp::client::EntityTemplate::ParallaxDef::opacity, rtp::ecs::components::Sprite::opacity, parallax, rtp::client::EntityTemplate::ParallaxDef::parallaxSpeed, position, rtp::client::EntityTemplate::ParallaxDef::rectHeight, rtp::ecs::components::Sprite::rectHeight, rtp::ecs::components::Sprite::rectLeft, rtp::ecs::components::Sprite::rectTop, rtp::client::EntityTemplate::ParallaxDef::rectWidth, rtp::ecs::components::Sprite::rectWidth, rtp::ecs::components::Sprite::red, rotation, rtp::client::EntityTemplate::ParallaxDef::scale, scale, rtp::ecs::components::ParallaxLayer::speed, rtp::ecs::components::Velocity::speed, sprite, rtp::client::EntityTemplate::ParallaxDef::texturePath, rtp::ecs::components::Sprite::texturePath, rtp::client::EntityTemplate::ParallaxDef::textureWidth, rtp::ecs::components::ParallaxLayer::textureWidth, velocity, rtp::client::EntityTemplate::ParallaxDef::velocityDir, rtp::client::EntityTemplate::ParallaxDef::velocitySpeed, withParallax, withVelocity, and rtp::ecs::components::Sprite::zIndex.
Referenced by createParallaxLvl2_1(), createParallaxLvl2_2(), createParallaxLvl2_3(), createParallaxLvl2_4(), createParallaxLvl2_5(), createParallaxLvl2_6(), createParallaxLvl3_1(), createParallaxLvl3_2(), createParallaxLvl3_3(), createParallaxLvl3_4(), createParallaxLvl3_5(), createParallaxLvl3_6(), createParallaxLvl3_7(), createParallaxLvl3_8(), createParallaxLvl3_9(), createParallaxLvl4_1(), createParallaxLvl4_2(), createParallaxLvl4_3(), createParallaxLvl4_4(), createParallaxLvl4_5(), createParallaxLvl4_6(), createParrallaxLvl1_1(), and createParrallaxLvl1_2().
player_ship()
EntityTemplate rtp::client::EntityTemplate::player_ship (const Vec2f & initialPos) inline static
Definition at line 552 of file EntityBuilder.hpp.
References k_rt1_1, and makeFromDef().
Referenced by rtp::client::NetworkSyncSystem::onSpawnEntityFromServer().
shot_1()
EntityTemplate rtp::client::EntityTemplate::shot_1 (const Vec2f & initialPos) inline static
Definition at line 567 of file EntityBuilder.hpp.
References k_rt1_4, and makeFromDef().
Referenced by rtp::client::NetworkSyncSystem::onSpawnEntityFromServer().
shot_2()
EntityTemplate rtp::client::EntityTemplate::shot_2 (const Vec2f & initialPos) inline static
Definition at line 572 of file EntityBuilder.hpp.
References k_rt1_5, and makeFromDef().
shot_3()
EntityTemplate rtp::client::EntityTemplate::shot_3 (const Vec2f & initialPos) inline static
Definition at line 577 of file EntityBuilder.hpp.
References k_rt1_6, and makeFromDef().
shot_4()
EntityTemplate rtp::client::EntityTemplate::shot_4 (const Vec2f & initialPos) inline static
Definition at line 582 of file EntityBuilder.hpp.
References k_rt1_7, and makeFromDef().
shot_5()
EntityTemplate rtp::client::EntityTemplate::shot_5 (const Vec2f & initialPos) inline static
Definition at line 587 of file EntityBuilder.hpp.
References k_rt1_8, and makeFromDef().
Referenced by rtp::client::NetworkSyncSystem::onBeamState().
shot_6()
EntityTemplate rtp::client::EntityTemplate::shot_6 (const Vec2f & initialPos) inline static
Definition at line 610 of file EntityBuilder.hpp.
References k_rt2_3, and makeFromDef().
shot_7()
EntityTemplate rtp::client::EntityTemplate::shot_7 (const Vec2f & initialPos) inline static
Definition at line 620 of file EntityBuilder.hpp.
References k_rt2_5, and makeFromDef().
shot_insane()
EntityTemplate rtp::client::EntityTemplate::shot_insane (const Vec2f & initialPos) inline static
Definition at line 557 of file EntityBuilder.hpp.
References k_rt1_2, and makeFromDef().
Member Data Documentation
animation
ecs::components::Animation rtp::client::EntityTemplate::animation {}
Initial animation data.
Definition at line 48 of file EntityBuilder.hpp.
Referenced by makeFromDef(), and rtp::client::EntityBuilder::update().
id
std::string rtp::client::EntityTemplate::id
Enemy type identifier.
Definition at line 33 of file EntityBuilder.hpp.
Referenced by makeFromDef(), and makeParallax().
k_rt1_1
SpriteAnimDef rtp::client::EntityTemplate::k_rt1_1 static constexpr
Initial value:
{
            "player_ship",     "assets/sprites/r-typesheet1.gif",
            101,         3,
            33,          14,
            5,           255,         255, 255,
            true,        33,
            14,          101,
            3,           5,
            2.0f,        {-1.0f, 0.0f},
            {1.0f,  1.0f}
        }
Definition at line 179 of file EntityBuilder.hpp.
Referenced by player_ship().
k_rt1_12
SpriteAnimDef rtp::client::EntityTemplate::k_rt1_12 static constexpr
Initial value:
{
            "effect_2",    "assets/sprites/r-typesheet1.gif",
            211,         276,
            16,          12,
            5,           255,         255, 255,
            true,        16,
            12,          211,
            276,         4,
            2.0f,        {-1.0f, 0.0f},
            {1.0f,  1.0f}
        }
Definition at line 267 of file EntityBuilder.hpp.
Referenced by effect_2().
k_rt1_13
SpriteAnimDef rtp::client::EntityTemplate::k_rt1_13 static constexpr
Initial value:
{
            "effect_3",    "assets/sprites/r-typesheet1.gif",
            72,          296,
            37,          30,
            5,           255,         255, 255,
            true,        37,
            30,          72,
            296,         6,
            2.0f,        {-1.0f, 0.0f},
            {1.0f,  1.0f}
        }
Definition at line 278 of file EntityBuilder.hpp.
Referenced by effect_3().
k_rt1_2
SpriteAnimDef rtp::client::EntityTemplate::k_rt1_2 static constexpr
Initial value:
{
            "shot_insane",     "assets/sprites/r-typesheet1.gif",
            134,         18,
            33,          32,
            5,           255,         255, 255,
            true,        33,
            32,          134,
            18,          4,
            2.0f,        {-1.0f, 0.0f},
            {1.0f,  1.0f}
        }
Definition at line 190 of file EntityBuilder.hpp.
Referenced by shot_insane().
k_rt1_3
SpriteAnimDef rtp::client::EntityTemplate::k_rt1_3 static constexpr
Initial value:
{
            "effect_1",     "assets/sprites/r-typesheet1.gif",
            2,           51,
            33,          32,
            5,           255,         255, 255,
            true,        33,
            32,          2,
            51,          8,
            2.0f,        {-1.0f, 0.0f},
            {1.0f,  1.0f}
        }
Definition at line 201 of file EntityBuilder.hpp.
Referenced by effect_1().
k_rt1_4
SpriteAnimDef rtp::client::EntityTemplate::k_rt1_4 static constexpr
Initial value:
{
            "shot_1",     "assets/sprites/r-typesheet1.gif",
            215,         85,
            18,          12,
            5,           255,         255, 255,
            true,        18,
            12,          215,
            85,          3,
            2.0f,        {-1.0f, 0.0f},
            {1.0f,  1.0f}
        }
Definition at line 212 of file EntityBuilder.hpp.
Referenced by shot_1().
k_rt1_5
SpriteAnimDef rtp::client::EntityTemplate::k_rt1_5 static constexpr
Initial value:
{
            "shot_2",     "assets/sprites/r-typesheet1.gif",
            232,         103,
            17,          12,
            5,           255,         255, 255,
            true,        17,
            12,          232,
            103,         2,
            2.0f,        {-1.0f, 0.0f},
            {1.0f,  1.0f}
        }
Definition at line 223 of file EntityBuilder.hpp.
Referenced by shot_2().
k_rt1_6
SpriteAnimDef rtp::client::EntityTemplate::k_rt1_6 static constexpr
Initial value:
{
            "shot_3",     "assets/sprites/r-typesheet1.gif",
            200,         121,
            33,          10,
            5,           255,         255, 255,
            true,        33,
            10,          200,
            121,         2,
            2.0f,        {-1.0f, 0.0f},
            {1.0f,  1.0f}
        }
Definition at line 234 of file EntityBuilder.hpp.
Referenced by shot_3().
k_rt1_7
SpriteAnimDef rtp::client::EntityTemplate::k_rt1_7 static constexpr
Initial value:
{
            "shot_4",     "assets/sprites/r-typesheet1.gif",
            168,         137,
            49,          12,
            5,           255,         255, 255,
            true,        49,
            12,          168,
            137,         2,
            2.0f,        {-1.0f, 0.0f},
            {1.0f,  1.0f}
        }
Definition at line 245 of file EntityBuilder.hpp.
Referenced by shot_4().
k_rt1_8
SpriteAnimDef rtp::client::EntityTemplate::k_rt1_8 static constexpr
Initial value:
{
            "shot_5",     "assets/sprites/r-typesheet1.gif",
            104,         171,
            81,          14,
            5,           255,         255, 255,
            true,        81,
            14,          104,
            171,         2,
            2.0f,        {-1.0f, 0.0f},
            {1.0f,  1.0f}
        }
Definition at line 256 of file EntityBuilder.hpp.
Referenced by shot_5().
k_rt2_2
SpriteAnimDef rtp::client::EntityTemplate::k_rt2_2 static constexpr
Initial value:
{
            "enemy_1",     "assets/sprites/r-typesheet2.gif",
            159,         35,
            24,          16,
            5,           255,         255, 255,
            true,        24,
            16,          159,
            35,          6,
            2.0f,        {-1.0f, 0.0f},
            {1.0f,  1.0f}
        }
Definition at line 290 of file EntityBuilder.hpp.
Referenced by createBasicScout2(), and enemy_1().
k_rt2_3
SpriteAnimDef rtp::client::EntityTemplate::k_rt2_3 static constexpr
Initial value:
{
            "shot_6",     "assets/sprites/r-typesheet2.gif",
            300,         58,
            18,          6,
            5,           255,         255, 255,
            false,       0,
            0,           0,
            0,           0,
            50.0f,       {-1.0f, 0.0f},
            {1.0f,  1.0f}
        }
Definition at line 301 of file EntityBuilder.hpp.
Referenced by createBulletEnemy(), createBulletPlayer(), and shot_6().
k_rt2_4
SpriteAnimDef rtp::client::EntityTemplate::k_rt2_4 static constexpr
Initial value:
{
            "enemy_2",     "assets/sprites/r-typesheet2.gif",
            300,         71,
            30,          18,
            5,           255,         255, 255,
            true,        30,
            18,          300,
            71,          6,
            2.0f,        {-1.0f, 0.0f},
            {1.0f,  1.0f}
        }
Definition at line 312 of file EntityBuilder.hpp.
Referenced by enemy_2().
k_rt2_5
SpriteAnimDef rtp::client::EntityTemplate::k_rt2_5 static constexpr
Initial value:
{
            "shot_7",     "assets/sprites/r-typesheet2.gif",
            266,         94,
            17,          10,
            5,           255,         255, 255,
            true,        17,
            10,          266,
            94,          2,
            2.0f,        {-1.0f, 0.0f},
            {1.0f,  1.0f}
        }
Definition at line 323 of file EntityBuilder.hpp.
Referenced by shot_7().
k_rt2_6
SpriteAnimDef rtp::client::EntityTemplate::k_rt2_6 static constexpr
Initial value:
{
            "effect_4",     "assets/sprites/r-typesheet2.gif",
            101,         118,
            17,          14,
            5,           255,         255, 255,
            true,        17,
            14,          101,
            118,         4,
            2.0f,        {-1.0f, 0.0f},
            {1.0f,  1.0f}
        }
Definition at line 334 of file EntityBuilder.hpp.
Referenced by effect_4().
k_rt2_7
SpriteAnimDef rtp::client::EntityTemplate::k_rt2_7 static constexpr
Initial value:
{
            "effect_5",     "assets/sprites/r-typesheet2.gif",
            157,         316,
            18,          14,
            5,           255,         255, 255,
            true,        18,
            14,          157,
            316,         8,
            2.0f,        {-1.0f, 0.0f},
            {1.0f,  1.0f}
        }
Definition at line 345 of file EntityBuilder.hpp.
Referenced by effect_5().
k_rt35_boss2
SpriteAnimDef rtp::client::EntityTemplate::k_rt35_boss2 static constexpr
Initial value:
{
            "boss2_kraken",   "assets/sprites/r-typesheet35.gif",
            0,          0,
            264,        143,
            5,          255,         200, 200,
            true,       264,
            143,        0,
            0,          8,
            0.5f,       {-1.0f, 0.0f},
            {1.5f,  1.5f}
        }
Definition at line 413 of file EntityBuilder.hpp.
Referenced by createBoss2Kraken().
k_rt35_boss2_bullet
SpriteAnimDef rtp::client::EntityTemplate::k_rt35_boss2_bullet static constexpr
Initial value:
{
            "boss2_bullet",   "assets/sprites/r-typesheet1.gif",
            215,        85,
            18,         12,
            5,          255,         100, 100,
            true,       18,
            12,         215,
            85,         3,
            5.0f,       {-1.0f, 0.0f},
            {2.0f,  2.0f}
        }
Definition at line 425 of file EntityBuilder.hpp.
Referenced by createBoss2Bullet().
k_rt39_1
SpriteAnimDef rtp::client::EntityTemplate::k_rt39_1 static constexpr
Initial value:
{
            "boss_ship",    "assets/sprites/r-typesheet39.gif",
            33,          1,
            66,         66,
            5,          255,         255, 255,
            false,       66,
            33,         66,
            1,          0,
            1.0f,        {-1.0f, 0.0f},
            {3.0f,  3.0f}
        }
Definition at line 389 of file EntityBuilder.hpp.
Referenced by createBossShip().
k_rt39_2
SpriteAnimDef rtp::client::EntityTemplate::k_rt39_2 static constexpr
Initial value:
{
            "boss_shield",    "assets/sprites/r-typesheet39.gif",
            0,          72,
            30,         33,
            5,          255,         255, 255,
            true,       33,
            30,         0,
            72,          4,
            1.0f,        {-1.0f, 0.0f},
            {3.0f,  3.0f}
        }
Definition at line 400 of file EntityBuilder.hpp.
Referenced by createBossShield().
k_rt3_1
SpriteAnimDef rtp::client::EntityTemplate::k_rt3_1 static constexpr
Initial value:
{
            "power_up_heal",     "assets/sprites/r-typesheet3.gif",
            0,           0,
            16,          16,
            5,           255,         255, 100,
            true,        16,
            16,          0,
            0,           12,
            2.0f,        {0.0f, 0.0f},
            {2.0f,  2.0f}
        }
Definition at line 356 of file EntityBuilder.hpp.
Referenced by createPowerUpHeal().
k_rt3_2
SpriteAnimDef rtp::client::EntityTemplate::k_rt3_2 static constexpr
Initial value:
{
            "power_up_double",   "assets/sprites/r-typesheet3.gif",
            64,          0,
            16,          16,
            5,           100,         200, 255,
            true,        16,
            16,          64,
            0,           12,
            2.0f,        {0.0f, 0.0f},
            {2.0f,  2.0f}
        }
Definition at line 367 of file EntityBuilder.hpp.
Referenced by createPowerUpDoubleFire().
k_rt3_3
SpriteAnimDef rtp::client::EntityTemplate::k_rt3_3 static constexpr
Initial value:
{
            "power_up_shield",   "assets/sprites/r-typesheet3.gif",
            128,         0,
            16,          16,
            5,           100,         255, 100,
            true,        16,
            16,          128,
            0,           12,
            2.0f,        {0.0f, 0.0f},
            {2.0f,  2.0f}
        }
Definition at line 378 of file EntityBuilder.hpp.
Referenced by createPowerUpShield().
kParallaxLvl1_1
ParallaxDef rtp::client::EntityTemplate::kParallaxLvl1_1 { "assets/backgrounds/lvl1/stars_far.png", 10.0f, {-50.0f, 0.0f}, 200, 100.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 } static constexpr
Definition at line 155 of file EntityBuilder.hpp.
Referenced by createParrallaxLvl1_1().
kParallaxLvl1_2
ParallaxDef rtp::client::EntityTemplate::kParallaxLvl1_2 { "assets/backgrounds/lvl1/stars_near.png", 20.0f, {-50.0f, 0.0f}, 255, 300.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 } static constexpr
Definition at line 156 of file EntityBuilder.hpp.
Referenced by createParrallaxLvl1_2().
kParallaxLvl2_1
ParallaxDef rtp::client::EntityTemplate::kParallaxLvl2_1 { "assets/backgrounds/lvl2/moon_back.png", 10.0f, {0.0f, 0.0f}, 200, 80.0f, 1200.0f, {1.0f, 1.0f}, 1300, 720 } static constexpr
Definition at line 157 of file EntityBuilder.hpp.
Referenced by createParallaxLvl2_1().
kParallaxLvl2_2
ParallaxDef rtp::client::EntityTemplate::kParallaxLvl2_2 { "assets/backgrounds/lvl2/moon_earth.png", 25.0f, {-30.0f, 0.0f}, 255, 150.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 } static constexpr
Definition at line 158 of file EntityBuilder.hpp.
Referenced by createParallaxLvl2_2().
kParallaxLvl2_3
ParallaxDef rtp::client::EntityTemplate::kParallaxLvl2_3 { "assets/backgrounds/lvl2/moon_floor.png", 12.0f, {-20.0f, 0.0f}, 200, 60.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 } static constexpr
Definition at line 159 of file EntityBuilder.hpp.
Referenced by createParallaxLvl2_3().
kParallaxLvl2_4
ParallaxDef rtp::client::EntityTemplate::kParallaxLvl2_4 { "assets/backgrounds/lvl2/moon_front.png", 18.0f, {-40.0f, 0.0f}, 200, 90.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 } static constexpr
Definition at line 160 of file EntityBuilder.hpp.
Referenced by createParallaxLvl2_4().
kParallaxLvl2_5
ParallaxDef rtp::client::EntityTemplate::kParallaxLvl2_5 { "assets/backgrounds/lvl2/moon_mid.png", 20.0f, {-25.0f, 0.0f}, 255, 70.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 } static constexpr
Definition at line 161 of file EntityBuilder.hpp.
Referenced by createParallaxLvl2_5().
kParallaxLvl2_6
ParallaxDef rtp::client::EntityTemplate::kParallaxLvl2_6 { "assets/backgrounds/lvl2/moon_sky.png", 10.0f, {-15.0f, 0.0f}, 200, 50.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 } static constexpr
Definition at line 162 of file EntityBuilder.hpp.
Referenced by createParallaxLvl2_6().
kParallaxLvl3_1
ParallaxDef rtp::client::EntityTemplate::kParallaxLvl3_1 { "assets/backgrounds/lvl3/Sky_back_mountain.png", 15.0f, {-20.0f, 0.0f}, 255, 60.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 } static constexpr
Definition at line 163 of file EntityBuilder.hpp.
Referenced by createParallaxLvl3_1().
kParallaxLvl3_2
ParallaxDef rtp::client::EntityTemplate::kParallaxLvl3_2 { "assets/backgrounds/lvl3/sky_cloud_floor_2.png", 22.0f, {-35.0f, 0.0f}, 200, 85.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 } static constexpr
Definition at line 164 of file EntityBuilder.hpp.
Referenced by createParallaxLvl3_2().
kParallaxLvl3_3
ParallaxDef rtp::client::EntityTemplate::kParallaxLvl3_3 { "assets/backgrounds/lvl3/sky_cloud_floor.png", 18.0f, {-25.0f, 0.0f}, 255, 70.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 } static constexpr
Definition at line 165 of file EntityBuilder.hpp.
Referenced by createParallaxLvl3_3().
kParallaxLvl3_4
ParallaxDef rtp::client::EntityTemplate::kParallaxLvl3_4 { "assets/backgrounds/lvl3/Sky_cloud_single.png", 20.0f, {-30.0f, 0.0f}, 255, 90.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 } static constexpr
Definition at line 166 of file EntityBuilder.hpp.
Referenced by createParallaxLvl3_4().
kParallaxLvl3_5
ParallaxDef rtp::client::EntityTemplate::kParallaxLvl3_5 { "assets/backgrounds/lvl3/sky_clouds.png", 12.0f, {-15.0f, 0.0f}, 200, 55.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 } static constexpr
Definition at line 167 of file EntityBuilder.hpp.
Referenced by createParallaxLvl3_5().
kParallaxLvl3_6
ParallaxDef rtp::client::EntityTemplate::kParallaxLvl3_6 { "assets/backgrounds/lvl3/Sky_front_cloud.png", 12.0f, {-15.0f, 0.0f}, 200, 55.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 } static constexpr
Definition at line 168 of file EntityBuilder.hpp.
Referenced by createParallaxLvl3_6().
kParallaxLvl3_7
ParallaxDef rtp::client::EntityTemplate::kParallaxLvl3_7 { "assets/backgrounds/lvl3/sky_front_mountain.png", 12.0f, {-15.0f, 0.0f}, 200, 55.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 } static constexpr
Definition at line 169 of file EntityBuilder.hpp.
Referenced by createParallaxLvl3_7().
kParallaxLvl3_8
ParallaxDef rtp::client::EntityTemplate::kParallaxLvl3_8 { "assets/backgrounds/lvl3/sky_moon.png", 12.0f, {-15.0f, 0.0f}, 200, 55.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 } static constexpr
Definition at line 170 of file EntityBuilder.hpp.
Referenced by createParallaxLvl3_8().
kParallaxLvl3_9
ParallaxDef rtp::client::EntityTemplate::kParallaxLvl3_9 { "assets/backgrounds/lvl3/Sky_sky.png", 12.0f, {-15.0f, 0.0f}, 200, 55.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 } static constexpr
Definition at line 171 of file EntityBuilder.hpp.
Referenced by createParallaxLvl3_9().
kParallaxLvl4_1
ParallaxDef rtp::client::EntityTemplate::kParallaxLvl4_1 { "assets/backgrounds/lvl4/desert_cloud.png", 15.0f, {-30.0f, 0.0f}, 200, 80.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 } static constexpr
Definition at line 172 of file EntityBuilder.hpp.
Referenced by createParallaxLvl4_1().
kParallaxLvl4_2
ParallaxDef rtp::client::EntityTemplate::kParallaxLvl4_2 { "assets/backgrounds/lvl4/desert_dunefrontt.png", 25.0f, {-30.0f, 0.0f}, 255, 150.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 } static constexpr
Definition at line 173 of file EntityBuilder.hpp.
Referenced by createParallaxLvl4_2().
kParallaxLvl4_3
ParallaxDef rtp::client::EntityTemplate::kParallaxLvl4_3 { "assets/backgrounds/lvl4/desert_dunemid.png", 12.0f, {-20.0f, 0.0f}, 200, 60.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 } static constexpr
Definition at line 174 of file EntityBuilder.hpp.
Referenced by createParallaxLvl4_3().
kParallaxLvl4_4
ParallaxDef rtp::client::EntityTemplate::kParallaxLvl4_4 { "assets/backgrounds/lvl4/desert_moon.png", 18.0f, {-40.0f, 0.0f}, 200, 90.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 } static constexpr
Definition at line 175 of file EntityBuilder.hpp.
Referenced by createParallaxLvl4_4().
kParallaxLvl4_5
ParallaxDef rtp::client::EntityTemplate::kParallaxLvl4_5 { "assets/backgrounds/lvl4/desert_mountain.png", 20.0f, {-25.0f, 0.0f}, 255, 70.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 } static constexpr
Definition at line 176 of file EntityBuilder.hpp.
Referenced by createParallaxLvl4_5().
kParallaxLvl4_6
ParallaxDef rtp::client::EntityTemplate::kParallaxLvl4_6 { "assets/backgrounds/lvl4/desert_sky.png", 10.0f, {-15.0f, 0.0f}, 200, 50.0f, 1280.0f, {2.0f, 2.0f}, 1280, 720 } static constexpr
Definition at line 177 of file EntityBuilder.hpp.
Referenced by createParallaxLvl4_6().
parallax
ecs::components::ParallaxLayer rtp::client::EntityTemplate::parallax {}
Parallax layer data.
Definition at line 53 of file EntityBuilder.hpp.
Referenced by makeParallax(), and rtp::client::scenes::MenuScene::onEnter().
position
Vec2f rtp::client::EntityTemplate::position {0.0f, 0.0f}
Spawn position.
Definition at line 36 of file EntityBuilder.hpp.
Referenced by makeFromDef(), makeParallax(), rtp::client::NetworkSyncSystem::onBeamState(), rtp::client::scenes::MenuScene::onEnter(), and rtp::client::EntityBuilder::update().
rotation
float rtp::client::EntityTemplate::rotation {0.0f}
Spawn rotation.
Definition at line 37 of file EntityBuilder.hpp.
Referenced by makeFromDef(), makeParallax(), rtp::client::NetworkSyncSystem::onBeamState(), and rtp::client::EntityBuilder::update().
scale
Vec2f rtp::client::EntityTemplate::scale {1.0f, 1.0f}
Spawn scale.
Definition at line 38 of file EntityBuilder.hpp.
Referenced by makeFromDef(), makeParallax(), rtp::client::NetworkSyncSystem::onBeamState(), rtp::client::scenes::MenuScene::onEnter(), rtp::client::NetworkSyncSystem::onSpawnEntityFromServer(), and rtp::client::EntityBuilder::update().
sprite
ecs::components::Sprite rtp::client::EntityTemplate::sprite {}
Sprite data.
Definition at line 43 of file EntityBuilder.hpp.
Referenced by makeFromDef(), makeParallax(), and rtp::client::EntityBuilder::update().
tag
std::string rtp::client::EntityTemplate::tag {}
Template tag for entity differentiation.
Definition at line 34 of file EntityBuilder.hpp.
Referenced by rtp::client::NetworkSyncSystem::onBeamState(), and rtp::client::NetworkSyncSystem::onSpawnEntityFromServer().
velocity
ecs::components::Velocity rtp::client::EntityTemplate::velocity {}
Initial velocity.
Definition at line 41 of file EntityBuilder.hpp.
Referenced by makeFromDef(), makeParallax(), and rtp::client::EntityBuilder::update().
withAnimation
bool rtp::client::EntityTemplate::withAnimation
Initial value:
{
            false}
Whether to add Animation component.
Definition at line 45 of file EntityBuilder.hpp.
Referenced by makeFromDef(), and rtp::client::EntityBuilder::update().
withParallax
bool rtp::client::EntityTemplate::withParallax
Initial value:
{
            false}
Whether to add ParallaxLayer component.
Definition at line 50 of file EntityBuilder.hpp.
Referenced by makeParallax().
withVelocity
bool rtp::client::EntityTemplate::withVelocity {false}
Whether to add Velocity component.
Definition at line 40 of file EntityBuilder.hpp.
Referenced by makeFromDef(), makeParallax(), and rtp::client::EntityBuilder::update().
The documentation for this struct was generated from the following file:
client/include/Game/EntityBuilder.hpp