Air-Trap: server/src/Systems/test_sparsearray.cpp File Reference
test_sparsearray.cpp File Reference
#include <gtest/gtest.h>
#include "RType/ECS/SparseArray.hpp"
#include "RType/ECS/Entity.hpp"
Classes
struct DummyComponent
Functions
TEST (SparseArrayTest, EraseNonExistingIsNoop)
TEST (SparseArrayTest, OverwriteKeepsSizeOne)
TEST (SparseArrayTest, EraseSwapBackMaintainsMapping)
TEST (SparseArrayTest, EntitiesAndDataSizesStayConsistent)
Function Documentation
TEST() [1/4]
TEST (SparseArrayTest , EntitiesAndDataSizesStayConsistent)
Definition at line 50 of file test_sparsearray.cpp.
References rtp::ecs::SparseArray< T >::emplace(), rtp::ecs::SparseArray< T >::entities(), rtp::ecs::SparseArray< T >::erase(), and rtp::ecs::SparseArray< T >::size().
TEST() [2/4]
TEST (SparseArrayTest , EraseNonExistingIsNoop)
Definition at line 11 of file test_sparsearray.cpp.
References rtp::ecs::SparseArray< T >::empty(), rtp::ecs::SparseArray< T >::erase(), and rtp::ecs::SparseArray< T >::size().
TEST() [3/4]
TEST (SparseArrayTest , EraseSwapBackMaintainsMapping)
Definition at line 28 of file test_sparsearray.cpp.
References rtp::ecs::SparseArray< T >::emplace(), rtp::ecs::SparseArray< T >::erase(), rtp::ecs::SparseArray< T >::has(), and rtp::ecs::SparseArray< T >::size().
TEST() [4/4]
TEST (SparseArrayTest , OverwriteKeepsSizeOne)
Definition at line 19 of file test_sparsearray.cpp.
References rtp::ecs::SparseArray< T >::emplace(), and rtp::ecs::SparseArray< T >::size().